################################################################################
# Automatically-generated file. Do not edit!
################################################################################

OBJ_UPPER_SRCS := 
ASM_UPPER_SRCS := 
ASM_SRCS := 
SX_UPPER_SRCS := 
O_UPPER_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
C_UPPER_SRCS := 
OBJ_SRCS := 
S_SRCS := 
SX_SRCS := 
LINKER_SCRIPT := 
JMP_UPPER_SRCS := 
PP_SRCS := 
P_UPPER_SRCS := 
SRC_UPPER_SRCS := 
FSY_SRCS := 
P_SRCS := 
SRC_SRCS := 
JMP_SRCS := 
C_SRCS := 
FSY_UPPER_SRCS := 
PP_UPPER_SRCS := 
JMP_DEPS := 
FSY_DEPS := 
C_UPPER_DEPS := 
ARCHIVES := 
SRC_UPPER_DEPS := 
P_UPPER_DEPS := 
S_DEPS := 
PP_UPPER_DEPS := 
P_DEPS := 
FSY_UPPER_DEPS := 
C_DEPS := 
SRC_DEPS := 
JMP_UPPER_DEPS := 
PP_DEPS := 
ASM_UPPER_DEPS := 
SX_DEPS := 
SX_UPPER_DEPS := 
OBJS := 
ASM_DEPS := 
S_UPPER_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
azure/ports/cortex_a9/gnu/src \
src/arm/cmsis/src \
src/renesas/application \
src/renesas/application/graphics \
src/renesas/application/system \
src/renesas/application/system/reference/inc \
src/renesas/compiler/asm \
src/renesas/compiler/init \
src/renesas/compiler \
src/renesas/configuration/os_abstraction/doc \
src/renesas/configuration/os_abstraction/src \
src/renesas/configuration/sc \
src/renesas/drivers/adc \
src/renesas/drivers/intc \
src/renesas/drivers/ostm/src/hld \
src/renesas/drivers/ostm/src/lld \
src/renesas/drivers/ostm/src/sc \
src/renesas/drivers/r_cache \
src/renesas/drivers/r_ceu/porting \
src/renesas/drivers/r_ceu/src \
src/renesas/drivers/r_dmac/src/hld \
src/renesas/drivers/r_dmac/src/lld \
src/renesas/drivers/r_eeprom/src \
src/renesas/drivers/r_i2c/src/hld \
src/renesas/drivers/r_i2c/src/lld \
src/renesas/drivers/r_jcu/porting \
src/renesas/drivers/r_jcu/src \
src/renesas/drivers/r_jcu/userdef \
src/renesas/drivers/r_l2cc \
src/renesas/drivers/r_led/src \
src/renesas/drivers/r_rspi/src \
src/renesas/drivers/r_rtc/src/hld \
src/renesas/drivers/r_rtc/src/lld \
src/renesas/drivers/r_sci/src/hld \
src/renesas/drivers/r_sci/src/lld \
src/renesas/drivers/r_ssif/src/hld \
src/renesas/drivers/r_ssif/src/lld \
src/renesas/drivers/r_switch/src \
src/renesas/drivers/r_vdc_vdec/porting \
src/renesas/drivers/r_vdc_vdec/vdc_h/src \
src/renesas/drivers/r_vdc_vdec/vdc_l/src \
src/renesas/drivers/r_vdc_vdec/vdec/src \
src/renesas/drivers/r_wdt/src/hld \
src/renesas/drivers/r_wdt/src/lld \
src/renesas \
src/renesas/middleware/cmos/src \
src/renesas/middleware/ethernet/src \
src/renesas/middleware/pmod_lcd/src \
src/renesas/middleware/riic_cat9554/src \
src/renesas/middleware/riic_max9856/src \
src/renesas/middleware/sound/src \
src/renesas/middleware/touch/src/lcd_controller/FT5216 \
src/renesas/middleware/touch/src/lcd_controller/FT5x06 \
src/renesas/middleware/touch/src/lcd_controller \
src/renesas/middleware/touch/src/touch \
src/renesas/middleware/video/src \

