################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../common/src/nx_arp_announce_send.c \
../common/src/nx_arp_dynamic_entries_invalidate.c \
../common/src/nx_arp_dynamic_entry_delete.c \
../common/src/nx_arp_dynamic_entry_set.c \
../common/src/nx_arp_enable.c \
../common/src/nx_arp_entry_allocate.c \
../common/src/nx_arp_entry_delete.c \
../common/src/nx_arp_gratuitous_send.c \
../common/src/nx_arp_hardware_address_find.c \
../common/src/nx_arp_info_get.c \
../common/src/nx_arp_initialize.c \
../common/src/nx_arp_interface_entries_delete.c \
../common/src/nx_arp_ip_address_find.c \
../common/src/nx_arp_packet_deferred_receive.c \
../common/src/nx_arp_packet_receive.c \
../common/src/nx_arp_packet_send.c \
../common/src/nx_arp_periodic_update.c \
../common/src/nx_arp_probe_send.c \
../common/src/nx_arp_queue_process.c \
../common/src/nx_arp_queue_send.c \
../common/src/nx_arp_static_entries_delete.c \
../common/src/nx_arp_static_entry_create.c \
../common/src/nx_arp_static_entry_delete.c \
../common/src/nx_arp_static_entry_delete_internal.c \
../common/src/nx_icmp_cleanup.c \
../common/src/nx_icmp_enable.c \
../common/src/nx_icmp_info_get.c \
../common/src/nx_icmp_interface_ping.c \
../common/src/nx_icmp_interface_ping6.c \
../common/src/nx_icmp_packet_process.c \
../common/src/nx_icmp_packet_receive.c \
../common/src/nx_icmp_ping.c \
../common/src/nx_icmp_ping6.c \
../common/src/nx_icmp_queue_process.c \
../common/src/nx_icmpv4_packet_process.c \
../common/src/nx_icmpv4_process_echo_reply.c \
../common/src/nx_icmpv4_process_echo_request.c \
../common/src/nx_icmpv4_send_error_message.c \
../common/src/nx_icmpv6_DAD_clear_NDCache_entry.c \
../common/src/nx_icmpv6_DAD_failure.c \
../common/src/nx_icmpv6_dest_table_add.c \
../common/src/nx_icmpv6_dest_table_find.c \
../common/src/nx_icmpv6_destination_table_periodic_update.c \
../common/src/nx_icmpv6_packet_process.c \
../common/src/nx_icmpv6_perform_DAD.c \
../common/src/nx_icmpv6_process_echo_reply.c \
../common/src/nx_icmpv6_process_echo_request.c \
../common/src/nx_icmpv6_process_na.c \
../common/src/nx_icmpv6_process_ns.c \
../common/src/nx_icmpv6_process_packet_too_big.c \
../common/src/nx_icmpv6_process_ra.c \
../common/src/nx_icmpv6_process_redirect.c \
../common/src/nx_icmpv6_send_error_message.c \
../common/src/nx_icmpv6_send_ns.c \
../common/src/nx_icmpv6_send_queued_packets.c \
../common/src/nx_icmpv6_send_rs.c \
../common/src/nx_icmpv6_validate_neighbor_message.c \
../common/src/nx_icmpv6_validate_options.c \
../common/src/nx_icmpv6_validate_ra.c \
../common/src/nx_igmp_enable.c \
../common/src/nx_igmp_info_get.c \
../common/src/nx_igmp_interface_report_send.c \
../common/src/nx_igmp_loopback_disable.c \
../common/src/nx_igmp_loopback_enable.c \
../common/src/nx_igmp_multicast_check.c \
../common/src/nx_igmp_multicast_interface_join.c \
../common/src/nx_igmp_multicast_interface_join_internal.c \
../common/src/nx_igmp_multicast_interface_leave.c \
../common/src/nx_igmp_multicast_interface_leave_internal.c \
../common/src/nx_igmp_multicast_join.c \
../common/src/nx_igmp_multicast_leave.c \
../common/src/nx_igmp_packet_process.c \
../common/src/nx_igmp_packet_receive.c \
../common/src/nx_igmp_periodic_processing.c \
../common/src/nx_igmp_queue_process.c \
../common/src/nx_invalidate_destination_entry.c \
../common/src/nx_ip_address_change_notify.c \
../common/src/nx_ip_address_get.c \
../common/src/nx_ip_address_set.c \
../common/src/nx_ip_auxiliary_packet_pool_set.c \
../common/src/nx_ip_checksum_compute.c \
../common/src/nx_ip_create.c \
../common/src/nx_ip_deferred_link_status_process.c \
../common/src/nx_ip_delete.c \
../common/src/nx_ip_delete_queue_clear.c \
../common/src/nx_ip_dispatch_process.c \
../common/src/nx_ip_driver_deferred_enable.c \
../common/src/nx_ip_driver_deferred_processing.c \
../common/src/nx_ip_driver_deferred_receive.c \
../common/src/nx_ip_driver_direct_command.c \
../common/src/nx_ip_driver_interface_direct_command.c \
../common/src/nx_ip_driver_link_status_event.c \
../common/src/nx_ip_driver_packet_send.c \
../common/src/nx_ip_fast_periodic_timer_entry.c \
../common/src/nx_ip_forward_packet_process.c \
../common/src/nx_ip_forwarding_disable.c \
../common/src/nx_ip_forwarding_enable.c \
../common/src/nx_ip_fragment_assembly.c \
../common/src/nx_ip_fragment_disable.c \
../common/src/nx_ip_fragment_enable.c \
../common/src/nx_ip_fragment_forward_packet.c \
../common/src/nx_ip_fragment_packet.c \
../common/src/nx_ip_fragment_timeout_check.c \
../common/src/nx_ip_gateway_address_clear.c \
../common/src/nx_ip_gateway_address_get.c \
../common/src/nx_ip_gateway_address_set.c \
../common/src/nx_ip_header_add.c \
../common/src/nx_ip_info_get.c \
../common/src/nx_ip_initialize.c \
../common/src/nx_ip_interface_address_get.c \
../common/src/nx_ip_interface_address_mapping_configure.c \
../common/src/nx_ip_interface_address_set.c \
../common/src/nx_ip_interface_attach.c \
../common/src/nx_ip_interface_capability_get.c \
../common/src/nx_ip_interface_capability_set.c \
../common/src/nx_ip_interface_detach.c \
../common/src/nx_ip_interface_info_get.c \
../common/src/nx_ip_interface_mtu_set.c \
../common/src/nx_ip_interface_physical_address_get.c \
../common/src/nx_ip_interface_physical_address_set.c \
../common/src/nx_ip_interface_status_check.c \
../common/src/nx_ip_link_status_change_notify_set.c \
../common/src/nx_ip_max_payload_size_find.c \
../common/src/nx_ip_packet_checksum_compute.c \
../common/src/nx_ip_packet_deferred_receive.c \
../common/src/nx_ip_packet_receive.c \
../common/src/nx_ip_packet_send.c \
../common/src/nx_ip_periodic_timer_entry.c \
../common/src/nx_ip_raw_packet_cleanup.c \
../common/src/nx_ip_raw_packet_disable.c \
../common/src/nx_ip_raw_packet_enable.c \
../common/src/nx_ip_raw_packet_filter_set.c \
../common/src/nx_ip_raw_packet_processing.c \
../common/src/nx_ip_raw_packet_receive.c \
../common/src/nx_ip_raw_packet_send.c \
../common/src/nx_ip_raw_packet_source_send.c \
../common/src/nx_ip_raw_receive_queue_max_set.c \
../common/src/nx_ip_route_find.c \
../common/src/nx_ip_static_route_add.c \
../common/src/nx_ip_static_route_delete.c \
../common/src/nx_ip_status_check.c \
../common/src/nx_ip_thread_entry.c \
../common/src/nx_ipv4_multicast_interface_join.c \
../common/src/nx_ipv4_multicast_interface_leave.c \
../common/src/nx_ipv4_option_process.c \
../common/src/nx_ipv4_packet_receive.c \
../common/src/nx_ipv6_fragment_process.c \
../common/src/nx_ipv6_header_add.c \
../common/src/nx_ipv6_multicast_join.c \
../common/src/nx_ipv6_multicast_leave.c \
../common/src/nx_ipv6_option_error.c \
../common/src/nx_ipv6_packet_copy.c \
../common/src/nx_ipv6_packet_receive.c \
../common/src/nx_ipv6_packet_send.c \
../common/src/nx_ipv6_prefix_list_add_entry.c \
../common/src/nx_ipv6_prefix_list_delete.c \
../common/src/nx_ipv6_prefix_list_delete_entry.c \
../common/src/nx_ipv6_process_fragment_option.c \
../common/src/nx_ipv6_process_hop_by_hop_option.c \
../common/src/nx_ipv6_process_routing_option.c \
../common/src/nx_ipv6_util.c \
../common/src/nx_md5.c \
../common/src/nx_nd_cache_add.c \
../common/src/nx_nd_cache_add_entry.c \
../common/src/nx_nd_cache_delete_internal.c \
../common/src/nx_nd_cache_fast_periodic_update.c \
../common/src/nx_nd_cache_find_entry.c \
../common/src/nx_nd_cache_find_entry_by_mac_addr.c \
../common/src/nx_nd_cache_interface_entries_delete.c \
../common/src/nx_nd_cache_slow_periodic_update.c \
../common/src/nx_packet_allocate.c \
../common/src/nx_packet_copy.c \
../common/src/nx_packet_data_adjust.c \
../common/src/nx_packet_data_append.c \
../common/src/nx_packet_data_extract_offset.c \
../common/src/nx_packet_data_retrieve.c \
../common/src/nx_packet_debug_info_get.c \
../common/src/nx_packet_length_get.c \
../common/src/nx_packet_pool_cleanup.c \
../common/src/nx_packet_pool_create.c \
../common/src/nx_packet_pool_delete.c \
../common/src/nx_packet_pool_info_get.c \
../common/src/nx_packet_pool_initialize.c \
../common/src/nx_packet_pool_low_watermark_set.c \
../common/src/nx_packet_release.c \
../common/src/nx_packet_transmit_release.c \
../common/src/nx_ram_network_driver.c \
../common/src/nx_rarp_disable.c \
../common/src/nx_rarp_enable.c \
../common/src/nx_rarp_info_get.c \
../common/src/nx_rarp_packet_deferred_receive.c \
../common/src/nx_rarp_packet_receive.c \
../common/src/nx_rarp_packet_send.c \
../common/src/nx_rarp_periodic_update.c \
../common/src/nx_rarp_queue_process.c \
../common/src/nx_system_initialize.c \
../common/src/nx_tcp_cleanup_deferred.c \
../common/src/nx_tcp_client_bind_cleanup.c \
../common/src/nx_tcp_client_socket_bind.c \
../common/src/nx_tcp_client_socket_connect.c \
../common/src/nx_tcp_client_socket_port_get.c \
../common/src/nx_tcp_client_socket_unbind.c \
../common/src/nx_tcp_connect_cleanup.c \
../common/src/nx_tcp_deferred_cleanup_check.c \
../common/src/nx_tcp_disconnect_cleanup.c \
../common/src/nx_tcp_enable.c \
../common/src/nx_tcp_fast_periodic_processing.c \
../common/src/nx_tcp_free_port_find.c \
../common/src/nx_tcp_info_get.c \
../common/src/nx_tcp_initialize.c \
../common/src/nx_tcp_mss_option_get.c \
../common/src/nx_tcp_no_connection_reset.c \
../common/src/nx_tcp_packet_process.c \
../common/src/nx_tcp_packet_receive.c \
../common/src/nx_tcp_packet_send_ack.c \
../common/src/nx_tcp_packet_send_control.c \
../common/src/nx_tcp_packet_send_fin.c \
../common/src/nx_tcp_packet_send_probe.c \
../common/src/nx_tcp_packet_send_rst.c \
../common/src/nx_tcp_packet_send_syn.c \
../common/src/nx_tcp_periodic_processing.c \
../common/src/nx_tcp_queue_process.c \
../common/src/nx_tcp_receive_cleanup.c \
../common/src/nx_tcp_server_socket_accept.c \
../common/src/nx_tcp_server_socket_listen.c \
../common/src/nx_tcp_server_socket_relisten.c \
../common/src/nx_tcp_server_socket_unaccept.c \
../common/src/nx_tcp_server_socket_unlisten.c \
../common/src/nx_tcp_socket_block_cleanup.c \
../common/src/nx_tcp_socket_bytes_available.c \
../common/src/nx_tcp_socket_connection_reset.c \
../common/src/nx_tcp_socket_create.c \
../common/src/nx_tcp_socket_delete.c \
../common/src/nx_tcp_socket_disconnect.c \
../common/src/nx_tcp_socket_disconnect_complete_notify.c \
../common/src/nx_tcp_socket_establish_notify.c \
../common/src/nx_tcp_socket_info_get.c \
../common/src/nx_tcp_socket_mss_get.c \
../common/src/nx_tcp_socket_mss_peer_get.c \
../common/src/nx_tcp_socket_mss_set.c \
../common/src/nx_tcp_socket_packet_process.c \
../common/src/nx_tcp_socket_peer_info_get.c \
../common/src/nx_tcp_socket_queue_depth_notify_set.c \
../common/src/nx_tcp_socket_receive.c \
../common/src/nx_tcp_socket_receive_notify.c \
../common/src/nx_tcp_socket_receive_queue_flush.c \
../common/src/nx_tcp_socket_receive_queue_max_set.c \
../common/src/nx_tcp_socket_retransmit.c \
../common/src/nx_tcp_socket_send.c \
../common/src/nx_tcp_socket_send_internal.c \
../common/src/nx_tcp_socket_state_ack_check.c \
../common/src/nx_tcp_socket_state_closing.c \
../common/src/nx_tcp_socket_state_data_check.c \
../common/src/nx_tcp_socket_state_established.c \
../common/src/nx_tcp_socket_state_fin_wait1.c \
../common/src/nx_tcp_socket_state_fin_wait2.c \
../common/src/nx_tcp_socket_state_last_ack.c \
../common/src/nx_tcp_socket_state_syn_received.c \
../common/src/nx_tcp_socket_state_syn_sent.c \
../common/src/nx_tcp_socket_state_transmit_check.c \
../common/src/nx_tcp_socket_state_wait.c \
../common/src/nx_tcp_socket_thread_resume.c \
../common/src/nx_tcp_socket_thread_suspend.c \
../common/src/nx_tcp_socket_timed_wait_callback.c \
../common/src/nx_tcp_socket_transmit_configure.c \
../common/src/nx_tcp_socket_transmit_queue_flush.c \
../common/src/nx_tcp_socket_window_update_notify_set.c \
../common/src/nx_tcp_transmit_cleanup.c \
../common/src/nx_tcp_window_scaling_option_get.c \
../common/src/nx_trace_event_insert.c \
../common/src/nx_trace_event_update.c \
../common/src/nx_trace_object_register.c \
../common/src/nx_trace_object_unregister.c \
../common/src/nx_udp_bind_cleanup.c \
../common/src/nx_udp_enable.c \
../common/src/nx_udp_free_port_find.c \
../common/src/nx_udp_info_get.c \
../common/src/nx_udp_packet_info_extract.c \
../common/src/nx_udp_packet_receive.c \
../common/src/nx_udp_receive_cleanup.c \
../common/src/nx_udp_socket_bind.c \
../common/src/nx_udp_socket_bytes_available.c \
../common/src/nx_udp_socket_checksum_disable.c \
../common/src/nx_udp_socket_checksum_enable.c \
../common/src/nx_udp_socket_create.c \
../common/src/nx_udp_socket_delete.c \
../common/src/nx_udp_socket_info_get.c \
../common/src/nx_udp_socket_port_get.c \
../common/src/nx_udp_socket_receive.c \
../common/src/nx_udp_socket_receive_notify.c \
../common/src/nx_udp_socket_send.c \
../common/src/nx_udp_socket_source_send.c \
../common/src/nx_udp_socket_unbind.c \
../common/src/nx_udp_source_extract.c \
../common/src/nx_utility.c \
../common/src/nxd_icmp_enable.c \
../common/src/nxd_icmp_ping.c \
../common/src/nxd_icmp_source_ping.c \
../common/src/nxd_icmpv6_ra_flag_callback_set.c \
../common/src/nxd_ip_raw_packet_send.c \
../common/src/nxd_ip_raw_packet_source_send.c \
../common/src/nxd_ipv6_address_change_notify.c \
../common/src/nxd_ipv6_address_delete.c \
../common/src/nxd_ipv6_address_get.c \
../common/src/nxd_ipv6_address_set.c \
../common/src/nxd_ipv6_default_router_add.c \
../common/src/nxd_ipv6_default_router_add_internal.c \
../common/src/nxd_ipv6_default_router_delete.c \
../common/src/nxd_ipv6_default_router_entry_get.c \
../common/src/nxd_ipv6_default_router_get.c \
../common/src/nxd_ipv6_default_router_number_of_entries_get.c \
../common/src/nxd_ipv6_default_router_table_init.c \
../common/src/nxd_ipv6_destination_table_find_next_hop.c \
../common/src/nxd_ipv6_disable.c \
../common/src/nxd_ipv6_enable.c \
../common/src/nxd_ipv6_find_default_router_from_address.c \
../common/src/nxd_ipv6_find_max_prefix_length.c \
../common/src/nxd_ipv6_interface_find.c \
../common/src/nxd_ipv6_multicast_interface_join.c \
../common/src/nxd_ipv6_multicast_interface_leave.c \
../common/src/nxd_ipv6_prefix_router_timer_tick.c \
../common/src/nxd_ipv6_raw_packet_send_internal.c \
../common/src/nxd_ipv6_router_lookup.c \
../common/src/nxd_ipv6_router_solicitation_check.c \
../common/src/nxd_ipv6_search_onlink.c \
../common/src/nxd_ipv6_stateless_address_autoconfig_disable.c \
../common/src/nxd_ipv6_stateless_address_autoconfig_enable.c \
../common/src/nxd_nd_cache_entry_delete.c \
../common/src/nxd_nd_cache_entry_set.c \
../common/src/nxd_nd_cache_hardware_address_find.c \
../common/src/nxd_nd_cache_invalidate.c \
../common/src/nxd_nd_cache_ip_address_find.c \
../common/src/nxd_tcp_client_socket_connect.c \
../common/src/nxd_tcp_socket_peer_info_get.c \
../common/src/nxd_udp_packet_info_extract.c \
../common/src/nxd_udp_socket_send.c \
../common/src/nxd_udp_socket_source_send.c \
../common/src/nxd_udp_source_extract.c \
../common/src/nxde_icmp_enable.c \
../common/src/nxde_icmp_ping.c \
../common/src/nxde_icmp_source_ping.c \
../common/src/nxde_icmpv6_ra_flag_callback_set.c \
../common/src/nxde_ip_raw_packet_send.c \
../common/src/nxde_ip_raw_packet_source_send.c \
../common/src/nxde_ipv6_address_change_notify.c \
../common/src/nxde_ipv6_address_delete.c \
../common/src/nxde_ipv6_address_get.c \
../common/src/nxde_ipv6_address_set.c \
../common/src/nxde_ipv6_default_router_add.c \
../common/src/nxde_ipv6_default_router_delete.c \
../common/src/nxde_ipv6_default_router_entry_get.c \
../common/src/nxde_ipv6_default_router_get.c \
../common/src/nxde_ipv6_default_router_number_of_entries_get.c \
../common/src/nxde_ipv6_disable.c \
../common/src/nxde_ipv6_enable.c \
../common/src/nxde_ipv6_multicast_interface_join.c \
../common/src/nxde_ipv6_multicast_interface_leave.c \
../common/src/nxde_ipv6_stateless_address_autoconfig_disable.c \
../common/src/nxde_ipv6_stateless_address_autoconfig_enable.c \
../common/src/nxde_nd_cache_entry_delete.c \
../common/src/nxde_nd_cache_entry_set.c \
../common/src/nxde_nd_cache_hardware_address_find.c \
../common/src/nxde_nd_cache_invalidate.c \
../common/src/nxde_nd_cache_ip_address_find.c \
../common/src/nxde_tcp_client_socket_connect.c \
../common/src/nxde_tcp_socket_peer_info_get.c \
../common/src/nxde_udp_packet_info_extract.c \
../common/src/nxde_udp_socket_send.c \
../common/src/nxde_udp_socket_source_send.c \
../common/src/nxde_udp_source_extract.c \
../common/src/nxe_arp_dynamic_entries_invalidate.c \
../common/src/nxe_arp_dynamic_entry_set.c \
../common/src/nxe_arp_enable.c \
../common/src/nxe_arp_entry_delete.c \
../common/src/nxe_arp_gratuitous_send.c \
../common/src/nxe_arp_hardware_address_find.c \
../common/src/nxe_arp_info_get.c \
../common/src/nxe_arp_ip_address_find.c \
../common/src/nxe_arp_static_entries_delete.c \
../common/src/nxe_arp_static_entry_create.c \
../common/src/nxe_arp_static_entry_delete.c \
../common/src/nxe_icmp_enable.c \
../common/src/nxe_icmp_info_get.c \
../common/src/nxe_icmp_ping.c \
../common/src/nxe_igmp_enable.c \
../common/src/nxe_igmp_info_get.c \
../common/src/nxe_igmp_loopback_disable.c \
../common/src/nxe_igmp_loopback_enable.c \
../common/src/nxe_igmp_multicast_interface_join.c \
../common/src/nxe_igmp_multicast_interface_leave.c \
../common/src/nxe_igmp_multicast_join.c \
../common/src/nxe_igmp_multicast_leave.c \
../common/src/nxe_ip_address_change_notify.c \
../common/src/nxe_ip_address_get.c \
../common/src/nxe_ip_address_set.c \
../common/src/nxe_ip_auxiliary_packet_pool_set.c \
../common/src/nxe_ip_create.c \
../common/src/nxe_ip_delete.c \
../common/src/nxe_ip_driver_direct_command.c \
../common/src/nxe_ip_driver_interface_direct_command.c \
../common/src/nxe_ip_forwarding_disable.c \
../common/src/nxe_ip_forwarding_enable.c \
../common/src/nxe_ip_fragment_disable.c \
../common/src/nxe_ip_fragment_enable.c \
../common/src/nxe_ip_gateway_address_clear.c \
../common/src/nxe_ip_gateway_address_get.c \
../common/src/nxe_ip_gateway_address_set.c \
../common/src/nxe_ip_info_get.c \
../common/src/nxe_ip_interface_address_get.c \
../common/src/nxe_ip_interface_address_mapping_configure.c \
../common/src/nxe_ip_interface_address_set.c \
../common/src/nxe_ip_interface_attach.c \
../common/src/nxe_ip_interface_capability_get.c \
../common/src/nxe_ip_interface_capability_set.c \
../common/src/nxe_ip_interface_detach.c \
../common/src/nxe_ip_interface_info_get.c \
../common/src/nxe_ip_interface_mtu_set.c \
../common/src/nxe_ip_interface_physical_address_get.c \
../common/src/nxe_ip_interface_physical_address_set.c \
../common/src/nxe_ip_interface_status_check.c \
../common/src/nxe_ip_link_status_change_notify_set.c \
../common/src/nxe_ip_max_payload_size_find.c \
../common/src/nxe_ip_raw_packet_disable.c \
../common/src/nxe_ip_raw_packet_enable.c \
../common/src/nxe_ip_raw_packet_filter_set.c \
../common/src/nxe_ip_raw_packet_receive.c \
../common/src/nxe_ip_raw_packet_send.c \
../common/src/nxe_ip_raw_packet_source_send.c \
../common/src/nxe_ip_raw_receive_queue_max_set.c \
../common/src/nxe_ip_static_route_add.c \
../common/src/nxe_ip_static_route_delete.c \
../common/src/nxe_ip_status_check.c \
../common/src/nxe_ipv4_multicast_interface_join.c \
../common/src/nxe_ipv4_multicast_interface_leave.c \
../common/src/nxe_packet_allocate.c \
../common/src/nxe_packet_copy.c \
../common/src/nxe_packet_data_append.c \
../common/src/nxe_packet_data_extract_offset.c \
../common/src/nxe_packet_data_retrieve.c \
../common/src/nxe_packet_length_get.c \
../common/src/nxe_packet_pool_create.c \
../common/src/nxe_packet_pool_delete.c \
../common/src/nxe_packet_pool_info_get.c \
../common/src/nxe_packet_pool_low_watermark_set.c \
../common/src/nxe_packet_release.c \
../common/src/nxe_packet_transmit_release.c \
../common/src/nxe_rarp_disable.c \
../common/src/nxe_rarp_enable.c \
../common/src/nxe_rarp_info_get.c \
../common/src/nxe_tcp_client_socket_bind.c \
../common/src/nxe_tcp_client_socket_connect.c \
../common/src/nxe_tcp_client_socket_port_get.c \
../common/src/nxe_tcp_client_socket_unbind.c \
../common/src/nxe_tcp_enable.c \
../common/src/nxe_tcp_free_port_find.c \
../common/src/nxe_tcp_info_get.c \
../common/src/nxe_tcp_server_socket_accept.c \
../common/src/nxe_tcp_server_socket_listen.c \
../common/src/nxe_tcp_server_socket_relisten.c \
../common/src/nxe_tcp_server_socket_unaccept.c \
../common/src/nxe_tcp_server_socket_unlisten.c \
../common/src/nxe_tcp_socket_bytes_available.c \
../common/src/nxe_tcp_socket_create.c \
../common/src/nxe_tcp_socket_delete.c \
../common/src/nxe_tcp_socket_disconnect.c \
../common/src/nxe_tcp_socket_disconnect_complete_notify.c \
../common/src/nxe_tcp_socket_establish_notify.c \
../common/src/nxe_tcp_socket_info_get.c \
../common/src/nxe_tcp_socket_mss_get.c \
../common/src/nxe_tcp_socket_mss_peer_get.c \
../common/src/nxe_tcp_socket_mss_set.c \
../common/src/nxe_tcp_socket_peer_info_get.c \
../common/src/nxe_tcp_socket_queue_depth_notify_set.c \
../common/src/nxe_tcp_socket_receive.c \
../common/src/nxe_tcp_socket_receive_notify.c \
../common/src/nxe_tcp_socket_receive_queue_max_set.c \
../common/src/nxe_tcp_socket_send.c \
../common/src/nxe_tcp_socket_state_wait.c \
../common/src/nxe_tcp_socket_timed_wait_callback.c \
../common/src/nxe_tcp_socket_transmit_configure.c \
../common/src/nxe_tcp_socket_window_update_notify_set.c \
../common/src/nxe_udp_enable.c \
../common/src/nxe_udp_free_port_find.c \
../common/src/nxe_udp_info_get.c \
../common/src/nxe_udp_packet_info_extract.c \
../common/src/nxe_udp_socket_bind.c \
../common/src/nxe_udp_socket_bytes_available.c \
../common/src/nxe_udp_socket_checksum_disable.c \
../common/src/nxe_udp_socket_checksum_enable.c \
../common/src/nxe_udp_socket_create.c \
../common/src/nxe_udp_socket_delete.c \
../common/src/nxe_udp_socket_info_get.c \
../common/src/nxe_udp_socket_port_get.c \
../common/src/nxe_udp_socket_receive.c \
../common/src/nxe_udp_socket_receive_notify.c \
../common/src/nxe_udp_socket_send.c \
../common/src/nxe_udp_socket_source_send.c \
../common/src/nxe_udp_socket_unbind.c \
../common/src/nxe_udp_source_extract.c 

C_DEPS += \
./common/src/nx_arp_announce_send.d \
./common/src/nx_arp_dynamic_entries_invalidate.d \
./common/src/nx_arp_dynamic_entry_delete.d \
./common/src/nx_arp_dynamic_entry_set.d \
./common/src/nx_arp_enable.d \
./common/src/nx_arp_entry_allocate.d \
./common/src/nx_arp_entry_delete.d \
./common/src/nx_arp_gratuitous_send.d \
./common/src/nx_arp_hardware_address_find.d \
./common/src/nx_arp_info_get.d \
./common/src/nx_arp_initialize.d \
./common/src/nx_arp_interface_entries_delete.d \
./common/src/nx_arp_ip_address_find.d \
./common/src/nx_arp_packet_deferred_receive.d \
./common/src/nx_arp_packet_receive.d \
./common/src/nx_arp_packet_send.d \
./common/src/nx_arp_periodic_update.d \
./common/src/nx_arp_probe_send.d \
./common/src/nx_arp_queue_process.d \
./common/src/nx_arp_queue_send.d \
./common/src/nx_arp_static_entries_delete.d \
./common/src/nx_arp_static_entry_create.d \
./common/src/nx_arp_static_entry_delete.d \
./common/src/nx_arp_static_entry_delete_internal.d \
./common/src/nx_icmp_cleanup.d \
./common/src/nx_icmp_enable.d \
./common/src/nx_icmp_info_get.d \
./common/src/nx_icmp_interface_ping.d \
./common/src/nx_icmp_interface_ping6.d \
./common/src/nx_icmp_packet_process.d \
./common/src/nx_icmp_packet_receive.d \
./common/src/nx_icmp_ping.d \
./common/src/nx_icmp_ping6.d \
./common/src/nx_icmp_queue_process.d \
./common/src/nx_icmpv4_packet_process.d \
./common/src/nx_icmpv4_process_echo_reply.d \
./common/src/nx_icmpv4_process_echo_request.d \
./common/src/nx_icmpv4_send_error_message.d \
./common/src/nx_icmpv6_DAD_clear_NDCache_entry.d \
./common/src/nx_icmpv6_DAD_failure.d \
./common/src/nx_icmpv6_dest_table_add.d \
./common/src/nx_icmpv6_dest_table_find.d \
./common/src/nx_icmpv6_destination_table_periodic_update.d \
./common/src/nx_icmpv6_packet_process.d \
./common/src/nx_icmpv6_perform_DAD.d \
./common/src/nx_icmpv6_process_echo_reply.d \
./common/src/nx_icmpv6_process_echo_request.d \
./common/src/nx_icmpv6_process_na.d \
./common/src/nx_icmpv6_process_ns.d \
./common/src/nx_icmpv6_process_packet_too_big.d \
./common/src/nx_icmpv6_process_ra.d \
./common/src/nx_icmpv6_process_redirect.d \
./common/src/nx_icmpv6_send_error_message.d \
./common/src/nx_icmpv6_send_ns.d \
./common/src/nx_icmpv6_send_queued_packets.d \
./common/src/nx_icmpv6_send_rs.d \
./common/src/nx_icmpv6_validate_neighbor_message.d \
./common/src/nx_icmpv6_validate_options.d \
./common/src/nx_icmpv6_validate_ra.d \
./common/src/nx_igmp_enable.d \
./common/src/nx_igmp_info_get.d \
./common/src/nx_igmp_interface_report_send.d \
./common/src/nx_igmp_loopback_disable.d \
./common/src/nx_igmp_loopback_enable.d \
./common/src/nx_igmp_multicast_check.d \
./common/src/nx_igmp_multicast_interface_join.d \
./common/src/nx_igmp_multicast_interface_join_internal.d \
./common/src/nx_igmp_multicast_interface_leave.d \
./common/src/nx_igmp_multicast_interface_leave_internal.d \
./common/src/nx_igmp_multicast_join.d \
./common/src/nx_igmp_multicast_leave.d \
./common/src/nx_igmp_packet_process.d \
./common/src/nx_igmp_packet_receive.d \
./common/src/nx_igmp_periodic_processing.d \
./common/src/nx_igmp_queue_process.d \
./common/src/nx_invalidate_destination_entry.d \
./common/src/nx_ip_address_change_notify.d \
./common/src/nx_ip_address_get.d \
./common/src/nx_ip_address_set.d \
./common/src/nx_ip_auxiliary_packet_pool_set.d \
./common/src/nx_ip_checksum_compute.d \
./common/src/nx_ip_create.d \
./common/src/nx_ip_deferred_link_status_process.d \
./common/src/nx_ip_delete.d \
./common/src/nx_ip_delete_queue_clear.d \
./common/src/nx_ip_dispatch_process.d \
./common/src/nx_ip_driver_deferred_enable.d \
./common/src/nx_ip_driver_deferred_processing.d \
./common/src/nx_ip_driver_deferred_receive.d \
./common/src/nx_ip_driver_direct_command.d \
./common/src/nx_ip_driver_interface_direct_command.d \
./common/src/nx_ip_driver_link_status_event.d \
./common/src/nx_ip_driver_packet_send.d \
./common/src/nx_ip_fast_periodic_timer_entry.d \
./common/src/nx_ip_forward_packet_process.d \
./common/src/nx_ip_forwarding_disable.d \
./common/src/nx_ip_forwarding_enable.d \
./common/src/nx_ip_fragment_assembly.d \
./common/src/nx_ip_fragment_disable.d \
./common/src/nx_ip_fragment_enable.d \
./common/src/nx_ip_fragment_forward_packet.d \
./common/src/nx_ip_fragment_packet.d \
./common/src/nx_ip_fragment_timeout_check.d \
./common/src/nx_ip_gateway_address_clear.d \
./common/src/nx_ip_gateway_address_get.d \
./common/src/nx_ip_gateway_address_set.d \
./common/src/nx_ip_header_add.d \
./common/src/nx_ip_info_get.d \
./common/src/nx_ip_initialize.d \
./common/src/nx_ip_interface_address_get.d \
./common/src/nx_ip_interface_address_mapping_configure.d \
./common/src/nx_ip_interface_address_set.d \
./common/src/nx_ip_interface_attach.d \
./common/src/nx_ip_interface_capability_get.d \
./common/src/nx_ip_interface_capability_set.d \
./common/src/nx_ip_interface_detach.d \
./common/src/nx_ip_interface_info_get.d \
./common/src/nx_ip_interface_mtu_set.d \
./common/src/nx_ip_interface_physical_address_get.d \
./common/src/nx_ip_interface_physical_address_set.d \
./common/src/nx_ip_interface_status_check.d \
./common/src/nx_ip_link_status_change_notify_set.d \
./common/src/nx_ip_max_payload_size_find.d \
./common/src/nx_ip_packet_checksum_compute.d \
./common/src/nx_ip_packet_deferred_receive.d \
./common/src/nx_ip_packet_receive.d \
./common/src/nx_ip_packet_send.d \
./common/src/nx_ip_periodic_timer_entry.d \
./common/src/nx_ip_raw_packet_cleanup.d \
./common/src/nx_ip_raw_packet_disable.d \
./common/src/nx_ip_raw_packet_enable.d \
./common/src/nx_ip_raw_packet_filter_set.d \
./common/src/nx_ip_raw_packet_processing.d \
./common/src/nx_ip_raw_packet_receive.d \
./common/src/nx_ip_raw_packet_send.d \
./common/src/nx_ip_raw_packet_source_send.d \
./common/src/nx_ip_raw_receive_queue_max_set.d \
./common/src/nx_ip_route_find.d \
./common/src/nx_ip_static_route_add.d \
./common/src/nx_ip_static_route_delete.d \
./common/src/nx_ip_status_check.d \
./common/src/nx_ip_thread_entry.d \
./common/src/nx_ipv4_multicast_interface_join.d \
./common/src/nx_ipv4_multicast_interface_leave.d \
./common/src/nx_ipv4_option_process.d \
./common/src/nx_ipv4_packet_receive.d \
./common/src/nx_ipv6_fragment_process.d \
./common/src/nx_ipv6_header_add.d \
./common/src/nx_ipv6_multicast_join.d \
./common/src/nx_ipv6_multicast_leave.d \
./common/src/nx_ipv6_option_error.d \
./common/src/nx_ipv6_packet_copy.d \
./common/src/nx_ipv6_packet_receive.d \
./common/src/nx_ipv6_packet_send.d \
./common/src/nx_ipv6_prefix_list_add_entry.d \
./common/src/nx_ipv6_prefix_list_delete.d \
./common/src/nx_ipv6_prefix_list_delete_entry.d \
./common/src/nx_ipv6_process_fragment_option.d \
./common/src/nx_ipv6_process_hop_by_hop_option.d \
./common/src/nx_ipv6_process_routing_option.d \
./common/src/nx_ipv6_util.d \
./common/src/nx_md5.d \
./common/src/nx_nd_cache_add.d \
./common/src/nx_nd_cache_add_entry.d \
./common/src/nx_nd_cache_delete_internal.d \
./common/src/nx_nd_cache_fast_periodic_update.d \
./common/src/nx_nd_cache_find_entry.d \
./common/src/nx_nd_cache_find_entry_by_mac_addr.d \
./common/src/nx_nd_cache_interface_entries_delete.d \
./common/src/nx_nd_cache_slow_periodic_update.d \
./common/src/nx_packet_allocate.d \
./common/src/nx_packet_copy.d \
./common/src/nx_packet_data_adjust.d \
./common/src/nx_packet_data_append.d \
./common/src/nx_packet_data_extract_offset.d \
./common/src/nx_packet_data_retrieve.d \
./common/src/nx_packet_debug_info_get.d \
./common/src/nx_packet_length_get.d \
./common/src/nx_packet_pool_cleanup.d \
./common/src/nx_packet_pool_create.d \
./common/src/nx_packet_pool_delete.d \
./common/src/nx_packet_pool_info_get.d \
./common/src/nx_packet_pool_initialize.d \
./common/src/nx_packet_pool_low_watermark_set.d \
./common/src/nx_packet_release.d \
./common/src/nx_packet_transmit_release.d \
./common/src/nx_ram_network_driver.d \
./common/src/nx_rarp_disable.d \
./common/src/nx_rarp_enable.d \
./common/src/nx_rarp_info_get.d \
./common/src/nx_rarp_packet_deferred_receive.d \
./common/src/nx_rarp_packet_receive.d \
./common/src/nx_rarp_packet_send.d \
./common/src/nx_rarp_periodic_update.d \
./common/src/nx_rarp_queue_process.d \
./common/src/nx_system_initialize.d \
./common/src/nx_tcp_cleanup_deferred.d \
./common/src/nx_tcp_client_bind_cleanup.d \
./common/src/nx_tcp_client_socket_bind.d \
./common/src/nx_tcp_client_socket_connect.d \
./common/src/nx_tcp_client_socket_port_get.d \
./common/src/nx_tcp_client_socket_unbind.d \
./common/src/nx_tcp_connect_cleanup.d \
./common/src/nx_tcp_deferred_cleanup_check.d \
./common/src/nx_tcp_disconnect_cleanup.d \
./common/src/nx_tcp_enable.d \
./common/src/nx_tcp_fast_periodic_processing.d \
./common/src/nx_tcp_free_port_find.d \
./common/src/nx_tcp_info_get.d \
./common/src/nx_tcp_initialize.d \
./common/src/nx_tcp_mss_option_get.d \
./common/src/nx_tcp_no_connection_reset.d \
./common/src/nx_tcp_packet_process.d \
./common/src/nx_tcp_packet_receive.d \
./common/src/nx_tcp_packet_send_ack.d \
./common/src/nx_tcp_packet_send_control.d \
./common/src/nx_tcp_packet_send_fin.d \
./common/src/nx_tcp_packet_send_probe.d \
./common/src/nx_tcp_packet_send_rst.d \
./common/src/nx_tcp_packet_send_syn.d \
./common/src/nx_tcp_periodic_processing.d \
./common/src/nx_tcp_queue_process.d \
./common/src/nx_tcp_receive_cleanup.d \
./common/src/nx_tcp_server_socket_accept.d \
./common/src/nx_tcp_server_socket_listen.d \
./common/src/nx_tcp_server_socket_relisten.d \
./common/src/nx_tcp_server_socket_unaccept.d \
./common/src/nx_tcp_server_socket_unlisten.d \
./common/src/nx_tcp_socket_block_cleanup.d \
./common/src/nx_tcp_socket_bytes_available.d \
./common/src/nx_tcp_socket_connection_reset.d \
./common/src/nx_tcp_socket_create.d \
./common/src/nx_tcp_socket_delete.d \
./common/src/nx_tcp_socket_disconnect.d \
./common/src/nx_tcp_socket_disconnect_complete_notify.d \
./common/src/nx_tcp_socket_establish_notify.d \
./common/src/nx_tcp_socket_info_get.d \
./common/src/nx_tcp_socket_mss_get.d \
./common/src/nx_tcp_socket_mss_peer_get.d \
./common/src/nx_tcp_socket_mss_set.d \
./common/src/nx_tcp_socket_packet_process.d \
./common/src/nx_tcp_socket_peer_info_get.d \
./common/src/nx_tcp_socket_queue_depth_notify_set.d \
./common/src/nx_tcp_socket_receive.d \
./common/src/nx_tcp_socket_receive_notify.d \
./common/src/nx_tcp_socket_receive_queue_flush.d \
./common/src/nx_tcp_socket_receive_queue_max_set.d \
./common/src/nx_tcp_socket_retransmit.d \
./common/src/nx_tcp_socket_send.d \
./common/src/nx_tcp_socket_send_internal.d \
./common/src/nx_tcp_socket_state_ack_check.d \
./common/src/nx_tcp_socket_state_closing.d \
./common/src/nx_tcp_socket_state_data_check.d \
./common/src/nx_tcp_socket_state_established.d \
./common/src/nx_tcp_socket_state_fin_wait1.d \
./common/src/nx_tcp_socket_state_fin_wait2.d \
./common/src/nx_tcp_socket_state_last_ack.d \
./common/src/nx_tcp_socket_state_syn_received.d \
./common/src/nx_tcp_socket_state_syn_sent.d \
./common/src/nx_tcp_socket_state_transmit_check.d \
./common/src/nx_tcp_socket_state_wait.d \
./common/src/nx_tcp_socket_thread_resume.d \
./common/src/nx_tcp_socket_thread_suspend.d \
./common/src/nx_tcp_socket_timed_wait_callback.d \
./common/src/nx_tcp_socket_transmit_configure.d \
./common/src/nx_tcp_socket_transmit_queue_flush.d \
./common/src/nx_tcp_socket_window_update_notify_set.d \
./common/src/nx_tcp_transmit_cleanup.d \
./common/src/nx_tcp_window_scaling_option_get.d \
./common/src/nx_trace_event_insert.d \
./common/src/nx_trace_event_update.d \
./common/src/nx_trace_object_register.d \
./common/src/nx_trace_object_unregister.d \
./common/src/nx_udp_bind_cleanup.d \
./common/src/nx_udp_enable.d \
./common/src/nx_udp_free_port_find.d \
./common/src/nx_udp_info_get.d \
./common/src/nx_udp_packet_info_extract.d \
./common/src/nx_udp_packet_receive.d \
./common/src/nx_udp_receive_cleanup.d \
./common/src/nx_udp_socket_bind.d \
./common/src/nx_udp_socket_bytes_available.d \
./common/src/nx_udp_socket_checksum_disable.d \
./common/src/nx_udp_socket_checksum_enable.d \
./common/src/nx_udp_socket_create.d \
./common/src/nx_udp_socket_delete.d \
./common/src/nx_udp_socket_info_get.d \
./common/src/nx_udp_socket_port_get.d \
./common/src/nx_udp_socket_receive.d \
./common/src/nx_udp_socket_receive_notify.d \
./common/src/nx_udp_socket_send.d \
./common/src/nx_udp_socket_source_send.d \
./common/src/nx_udp_socket_unbind.d \
./common/src/nx_udp_source_extract.d \
./common/src/nx_utility.d \
./common/src/nxd_icmp_enable.d \
./common/src/nxd_icmp_ping.d \
./common/src/nxd_icmp_source_ping.d \
./common/src/nxd_icmpv6_ra_flag_callback_set.d \
./common/src/nxd_ip_raw_packet_send.d \
./common/src/nxd_ip_raw_packet_source_send.d \
./common/src/nxd_ipv6_address_change_notify.d \
./common/src/nxd_ipv6_address_delete.d \
./common/src/nxd_ipv6_address_get.d \
./common/src/nxd_ipv6_address_set.d \
./common/src/nxd_ipv6_default_router_add.d \
./common/src/nxd_ipv6_default_router_add_internal.d \
./common/src/nxd_ipv6_default_router_delete.d \
./common/src/nxd_ipv6_default_router_entry_get.d \
./common/src/nxd_ipv6_default_router_get.d \
./common/src/nxd_ipv6_default_router_number_of_entries_get.d \
./common/src/nxd_ipv6_default_router_table_init.d \
./common/src/nxd_ipv6_destination_table_find_next_hop.d \
./common/src/nxd_ipv6_disable.d \
./common/src/nxd_ipv6_enable.d \
./common/src/nxd_ipv6_find_default_router_from_address.d \
./common/src/nxd_ipv6_find_max_prefix_length.d \
./common/src/nxd_ipv6_interface_find.d \
./common/src/nxd_ipv6_multicast_interface_join.d \
./common/src/nxd_ipv6_multicast_interface_leave.d \
./common/src/nxd_ipv6_prefix_router_timer_tick.d \
./common/src/nxd_ipv6_raw_packet_send_internal.d \
./common/src/nxd_ipv6_router_lookup.d \
./common/src/nxd_ipv6_router_solicitation_check.d \
./common/src/nxd_ipv6_search_onlink.d \
./common/src/nxd_ipv6_stateless_address_autoconfig_disable.d \
./common/src/nxd_ipv6_stateless_address_autoconfig_enable.d \
./common/src/nxd_nd_cache_entry_delete.d \
./common/src/nxd_nd_cache_entry_set.d \
./common/src/nxd_nd_cache_hardware_address_find.d \
./common/src/nxd_nd_cache_invalidate.d \
./common/src/nxd_nd_cache_ip_address_find.d \
./common/src/nxd_tcp_client_socket_connect.d \
./common/src/nxd_tcp_socket_peer_info_get.d \
./common/src/nxd_udp_packet_info_extract.d \
./common/src/nxd_udp_socket_send.d \
./common/src/nxd_udp_socket_source_send.d \
./common/src/nxd_udp_source_extract.d \
./common/src/nxde_icmp_enable.d \
./common/src/nxde_icmp_ping.d \
./common/src/nxde_icmp_source_ping.d \
./common/src/nxde_icmpv6_ra_flag_callback_set.d \
./common/src/nxde_ip_raw_packet_send.d \
./common/src/nxde_ip_raw_packet_source_send.d \
./common/src/nxde_ipv6_address_change_notify.d \
./common/src/nxde_ipv6_address_delete.d \
./common/src/nxde_ipv6_address_get.d \
./common/src/nxde_ipv6_address_set.d \
./common/src/nxde_ipv6_default_router_add.d \
./common/src/nxde_ipv6_default_router_delete.d \
./common/src/nxde_ipv6_default_router_entry_get.d \
./common/src/nxde_ipv6_default_router_get.d \
./common/src/nxde_ipv6_default_router_number_of_entries_get.d \
./common/src/nxde_ipv6_disable.d \
./common/src/nxde_ipv6_enable.d \
./common/src/nxde_ipv6_multicast_interface_join.d \
./common/src/nxde_ipv6_multicast_interface_leave.d \
./common/src/nxde_ipv6_stateless_address_autoconfig_disable.d \
./common/src/nxde_ipv6_stateless_address_autoconfig_enable.d \
./common/src/nxde_nd_cache_entry_delete.d \
./common/src/nxde_nd_cache_entry_set.d \
./common/src/nxde_nd_cache_hardware_address_find.d \
./common/src/nxde_nd_cache_invalidate.d \
./common/src/nxde_nd_cache_ip_address_find.d \
./common/src/nxde_tcp_client_socket_connect.d \
./common/src/nxde_tcp_socket_peer_info_get.d \
./common/src/nxde_udp_packet_info_extract.d \
./common/src/nxde_udp_socket_send.d \
./common/src/nxde_udp_socket_source_send.d \
./common/src/nxde_udp_source_extract.d \
./common/src/nxe_arp_dynamic_entries_invalidate.d \
./common/src/nxe_arp_dynamic_entry_set.d \
./common/src/nxe_arp_enable.d \
./common/src/nxe_arp_entry_delete.d \
./common/src/nxe_arp_gratuitous_send.d \
./common/src/nxe_arp_hardware_address_find.d \
./common/src/nxe_arp_info_get.d \
./common/src/nxe_arp_ip_address_find.d \
./common/src/nxe_arp_static_entries_delete.d \
./common/src/nxe_arp_static_entry_create.d \
./common/src/nxe_arp_static_entry_delete.d \
./common/src/nxe_icmp_enable.d \
./common/src/nxe_icmp_info_get.d \
./common/src/nxe_icmp_ping.d \
./common/src/nxe_igmp_enable.d \
./common/src/nxe_igmp_info_get.d \
./common/src/nxe_igmp_loopback_disable.d \
./common/src/nxe_igmp_loopback_enable.d \
./common/src/nxe_igmp_multicast_interface_join.d \
./common/src/nxe_igmp_multicast_interface_leave.d \
./common/src/nxe_igmp_multicast_join.d \
./common/src/nxe_igmp_multicast_leave.d \
./common/src/nxe_ip_address_change_notify.d \
./common/src/nxe_ip_address_get.d \
./common/src/nxe_ip_address_set.d \
./common/src/nxe_ip_auxiliary_packet_pool_set.d \
./common/src/nxe_ip_create.d \
./common/src/nxe_ip_delete.d \
./common/src/nxe_ip_driver_direct_command.d \
./common/src/nxe_ip_driver_interface_direct_command.d \
./common/src/nxe_ip_forwarding_disable.d \
./common/src/nxe_ip_forwarding_enable.d \
./common/src/nxe_ip_fragment_disable.d \
./common/src/nxe_ip_fragment_enable.d \
./common/src/nxe_ip_gateway_address_clear.d \
./common/src/nxe_ip_gateway_address_get.d \
./common/src/nxe_ip_gateway_address_set.d \
./common/src/nxe_ip_info_get.d \
./common/src/nxe_ip_interface_address_get.d \
./common/src/nxe_ip_interface_address_mapping_configure.d \
./common/src/nxe_ip_interface_address_set.d \
./common/src/nxe_ip_interface_attach.d \
./common/src/nxe_ip_interface_capability_get.d \
./common/src/nxe_ip_interface_capability_set.d \
./common/src/nxe_ip_interface_detach.d \
./common/src/nxe_ip_interface_info_get.d \
./common/src/nxe_ip_interface_mtu_set.d \
./common/src/nxe_ip_interface_physical_address_get.d \
./common/src/nxe_ip_interface_physical_address_set.d \
./common/src/nxe_ip_interface_status_check.d \
./common/src/nxe_ip_link_status_change_notify_set.d \
./common/src/nxe_ip_max_payload_size_find.d \
./common/src/nxe_ip_raw_packet_disable.d \
./common/src/nxe_ip_raw_packet_enable.d \
./common/src/nxe_ip_raw_packet_filter_set.d \
./common/src/nxe_ip_raw_packet_receive.d \
./common/src/nxe_ip_raw_packet_send.d \
./common/src/nxe_ip_raw_packet_source_send.d \
./common/src/nxe_ip_raw_receive_queue_max_set.d \
./common/src/nxe_ip_static_route_add.d \
./common/src/nxe_ip_static_route_delete.d \
./common/src/nxe_ip_status_check.d \
./common/src/nxe_ipv4_multicast_interface_join.d \
./common/src/nxe_ipv4_multicast_interface_leave.d \
./common/src/nxe_packet_allocate.d \
./common/src/nxe_packet_copy.d \
./common/src/nxe_packet_data_append.d \
./common/src/nxe_packet_data_extract_offset.d \
./common/src/nxe_packet_data_retrieve.d \
./common/src/nxe_packet_length_get.d \
./common/src/nxe_packet_pool_create.d \
./common/src/nxe_packet_pool_delete.d \
./common/src/nxe_packet_pool_info_get.d \
./common/src/nxe_packet_pool_low_watermark_set.d \
./common/src/nxe_packet_release.d \
./common/src/nxe_packet_transmit_release.d \
./common/src/nxe_rarp_disable.d \
./common/src/nxe_rarp_enable.d \
./common/src/nxe_rarp_info_get.d \
./common/src/nxe_tcp_client_socket_bind.d \
./common/src/nxe_tcp_client_socket_connect.d \
./common/src/nxe_tcp_client_socket_port_get.d \
./common/src/nxe_tcp_client_socket_unbind.d \
./common/src/nxe_tcp_enable.d \
./common/src/nxe_tcp_free_port_find.d \
./common/src/nxe_tcp_info_get.d \
./common/src/nxe_tcp_server_socket_accept.d \
./common/src/nxe_tcp_server_socket_listen.d \
./common/src/nxe_tcp_server_socket_relisten.d \
./common/src/nxe_tcp_server_socket_unaccept.d \
./common/src/nxe_tcp_server_socket_unlisten.d \
./common/src/nxe_tcp_socket_bytes_available.d \
./common/src/nxe_tcp_socket_create.d \
./common/src/nxe_tcp_socket_delete.d \
./common/src/nxe_tcp_socket_disconnect.d \
./common/src/nxe_tcp_socket_disconnect_complete_notify.d \
./common/src/nxe_tcp_socket_establish_notify.d \
./common/src/nxe_tcp_socket_info_get.d \
./common/src/nxe_tcp_socket_mss_get.d \
./common/src/nxe_tcp_socket_mss_peer_get.d \
./common/src/nxe_tcp_socket_mss_set.d \
./common/src/nxe_tcp_socket_peer_info_get.d \
./common/src/nxe_tcp_socket_queue_depth_notify_set.d \
./common/src/nxe_tcp_socket_receive.d \
./common/src/nxe_tcp_socket_receive_notify.d \
./common/src/nxe_tcp_socket_receive_queue_max_set.d \
./common/src/nxe_tcp_socket_send.d \
./common/src/nxe_tcp_socket_state_wait.d \
./common/src/nxe_tcp_socket_timed_wait_callback.d \
./common/src/nxe_tcp_socket_transmit_configure.d \
./common/src/nxe_tcp_socket_window_update_notify_set.d \
./common/src/nxe_udp_enable.d \
./common/src/nxe_udp_free_port_find.d \
./common/src/nxe_udp_info_get.d \
./common/src/nxe_udp_packet_info_extract.d \
./common/src/nxe_udp_socket_bind.d \
./common/src/nxe_udp_socket_bytes_available.d \
./common/src/nxe_udp_socket_checksum_disable.d \
./common/src/nxe_udp_socket_checksum_enable.d \
./common/src/nxe_udp_socket_create.d \
./common/src/nxe_udp_socket_delete.d \
./common/src/nxe_udp_socket_info_get.d \
./common/src/nxe_udp_socket_port_get.d \
./common/src/nxe_udp_socket_receive.d \
./common/src/nxe_udp_socket_receive_notify.d \
./common/src/nxe_udp_socket_send.d \
./common/src/nxe_udp_socket_source_send.d \
./common/src/nxe_udp_socket_unbind.d \
./common/src/nxe_udp_source_extract.d 

OBJS += \
./common/src/nx_arp_announce_send.o \
./common/src/nx_arp_dynamic_entries_invalidate.o \
./common/src/nx_arp_dynamic_entry_delete.o \
./common/src/nx_arp_dynamic_entry_set.o \
./common/src/nx_arp_enable.o \
./common/src/nx_arp_entry_allocate.o \
./common/src/nx_arp_entry_delete.o \
./common/src/nx_arp_gratuitous_send.o \
./common/src/nx_arp_hardware_address_find.o \
./common/src/nx_arp_info_get.o \
./common/src/nx_arp_initialize.o \
./common/src/nx_arp_interface_entries_delete.o \
./common/src/nx_arp_ip_address_find.o \
./common/src/nx_arp_packet_deferred_receive.o \
./common/src/nx_arp_packet_receive.o \
./common/src/nx_arp_packet_send.o \
./common/src/nx_arp_periodic_update.o \
./common/src/nx_arp_probe_send.o \
./common/src/nx_arp_queue_process.o \
./common/src/nx_arp_queue_send.o \
./common/src/nx_arp_static_entries_delete.o \
./common/src/nx_arp_static_entry_create.o \
./common/src/nx_arp_static_entry_delete.o \
./common/src/nx_arp_static_entry_delete_internal.o \
./common/src/nx_icmp_cleanup.o \
./common/src/nx_icmp_enable.o \
./common/src/nx_icmp_info_get.o \
./common/src/nx_icmp_interface_ping.o \
./common/src/nx_icmp_interface_ping6.o \
./common/src/nx_icmp_packet_process.o \
./common/src/nx_icmp_packet_receive.o \
./common/src/nx_icmp_ping.o \
./common/src/nx_icmp_ping6.o \
./common/src/nx_icmp_queue_process.o \
./common/src/nx_icmpv4_packet_process.o \
./common/src/nx_icmpv4_process_echo_reply.o \
./common/src/nx_icmpv4_process_echo_request.o \
./common/src/nx_icmpv4_send_error_message.o \
./common/src/nx_icmpv6_DAD_clear_NDCache_entry.o \
./common/src/nx_icmpv6_DAD_failure.o \
./common/src/nx_icmpv6_dest_table_add.o \
./common/src/nx_icmpv6_dest_table_find.o \
./common/src/nx_icmpv6_destination_table_periodic_update.o \
./common/src/nx_icmpv6_packet_process.o \
./common/src/nx_icmpv6_perform_DAD.o \
./common/src/nx_icmpv6_process_echo_reply.o \
./common/src/nx_icmpv6_process_echo_request.o \
./common/src/nx_icmpv6_process_na.o \
./common/src/nx_icmpv6_process_ns.o \
./common/src/nx_icmpv6_process_packet_too_big.o \
./common/src/nx_icmpv6_process_ra.o \
./common/src/nx_icmpv6_process_redirect.o \
./common/src/nx_icmpv6_send_error_message.o \
./common/src/nx_icmpv6_send_ns.o \
./common/src/nx_icmpv6_send_queued_packets.o \
./common/src/nx_icmpv6_send_rs.o \
./common/src/nx_icmpv6_validate_neighbor_message.o \
./common/src/nx_icmpv6_validate_options.o \
./common/src/nx_icmpv6_validate_ra.o \
./common/src/nx_igmp_enable.o \
./common/src/nx_igmp_info_get.o \
./common/src/nx_igmp_interface_report_send.o \
./common/src/nx_igmp_loopback_disable.o \
./common/src/nx_igmp_loopback_enable.o \
./common/src/nx_igmp_multicast_check.o \
./common/src/nx_igmp_multicast_interface_join.o \
./common/src/nx_igmp_multicast_interface_join_internal.o \
./common/src/nx_igmp_multicast_interface_leave.o \
./common/src/nx_igmp_multicast_interface_leave_internal.o \
./common/src/nx_igmp_multicast_join.o \
./common/src/nx_igmp_multicast_leave.o \
./common/src/nx_igmp_packet_process.o \
./common/src/nx_igmp_packet_receive.o \
./common/src/nx_igmp_periodic_processing.o \
./common/src/nx_igmp_queue_process.o \
./common/src/nx_invalidate_destination_entry.o \
./common/src/nx_ip_address_change_notify.o \
./common/src/nx_ip_address_get.o \
./common/src/nx_ip_address_set.o \
./common/src/nx_ip_auxiliary_packet_pool_set.o \
./common/src/nx_ip_checksum_compute.o \
./common/src/nx_ip_create.o \
./common/src/nx_ip_deferred_link_status_process.o \
./common/src/nx_ip_delete.o \
./common/src/nx_ip_delete_queue_clear.o \
./common/src/nx_ip_dispatch_process.o \
./common/src/nx_ip_driver_deferred_enable.o \
./common/src/nx_ip_driver_deferred_processing.o \
./common/src/nx_ip_driver_deferred_receive.o \
./common/src/nx_ip_driver_direct_command.o \
./common/src/nx_ip_driver_interface_direct_command.o \
./common/src/nx_ip_driver_link_status_event.o \
./common/src/nx_ip_driver_packet_send.o \
./common/src/nx_ip_fast_periodic_timer_entry.o \
./common/src/nx_ip_forward_packet_process.o \
./common/src/nx_ip_forwarding_disable.o \
./common/src/nx_ip_forwarding_enable.o \
./common/src/nx_ip_fragment_assembly.o \
./common/src/nx_ip_fragment_disable.o \
./common/src/nx_ip_fragment_enable.o \
./common/src/nx_ip_fragment_forward_packet.o \
./common/src/nx_ip_fragment_packet.o \
./common/src/nx_ip_fragment_timeout_check.o \
./common/src/nx_ip_gateway_address_clear.o \
./common/src/nx_ip_gateway_address_get.o \
./common/src/nx_ip_gateway_address_set.o \
./common/src/nx_ip_header_add.o \
./common/src/nx_ip_info_get.o \
./common/src/nx_ip_initialize.o \
./common/src/nx_ip_interface_address_get.o \
./common/src/nx_ip_interface_address_mapping_configure.o \
./common/src/nx_ip_interface_address_set.o \
./common/src/nx_ip_interface_attach.o \
./common/src/nx_ip_interface_capability_get.o \
./common/src/nx_ip_interface_capability_set.o \
./common/src/nx_ip_interface_detach.o \
./common/src/nx_ip_interface_info_get.o \
./common/src/nx_ip_interface_mtu_set.o \
./common/src/nx_ip_interface_physical_address_get.o \
./common/src/nx_ip_interface_physical_address_set.o \
./common/src/nx_ip_interface_status_check.o \
./common/src/nx_ip_link_status_change_notify_set.o \
./common/src/nx_ip_max_payload_size_find.o \
./common/src/nx_ip_packet_checksum_compute.o \
./common/src/nx_ip_packet_deferred_receive.o \
./common/src/nx_ip_packet_receive.o \
./common/src/nx_ip_packet_send.o \
./common/src/nx_ip_periodic_timer_entry.o \
./common/src/nx_ip_raw_packet_cleanup.o \
./common/src/nx_ip_raw_packet_disable.o \
./common/src/nx_ip_raw_packet_enable.o \
./common/src/nx_ip_raw_packet_filter_set.o \
./common/src/nx_ip_raw_packet_processing.o \
./common/src/nx_ip_raw_packet_receive.o \
./common/src/nx_ip_raw_packet_send.o \
./common/src/nx_ip_raw_packet_source_send.o \
./common/src/nx_ip_raw_receive_queue_max_set.o \
./common/src/nx_ip_route_find.o \
./common/src/nx_ip_static_route_add.o \
./common/src/nx_ip_static_route_delete.o \
./common/src/nx_ip_status_check.o \
./common/src/nx_ip_thread_entry.o \
./common/src/nx_ipv4_multicast_interface_join.o \
./common/src/nx_ipv4_multicast_interface_leave.o \
./common/src/nx_ipv4_option_process.o \
./common/src/nx_ipv4_packet_receive.o \
./common/src/nx_ipv6_fragment_process.o \
./common/src/nx_ipv6_header_add.o \
./common/src/nx_ipv6_multicast_join.o \
./common/src/nx_ipv6_multicast_leave.o \
./common/src/nx_ipv6_option_error.o \
./common/src/nx_ipv6_packet_copy.o \
./common/src/nx_ipv6_packet_receive.o \
./common/src/nx_ipv6_packet_send.o \
./common/src/nx_ipv6_prefix_list_add_entry.o \
./common/src/nx_ipv6_prefix_list_delete.o \
./common/src/nx_ipv6_prefix_list_delete_entry.o \
./common/src/nx_ipv6_process_fragment_option.o \
./common/src/nx_ipv6_process_hop_by_hop_option.o \
./common/src/nx_ipv6_process_routing_option.o \
./common/src/nx_ipv6_util.o \
./common/src/nx_md5.o \
./common/src/nx_nd_cache_add.o \
./common/src/nx_nd_cache_add_entry.o \
./common/src/nx_nd_cache_delete_internal.o \
./common/src/nx_nd_cache_fast_periodic_update.o \
./common/src/nx_nd_cache_find_entry.o \
./common/src/nx_nd_cache_find_entry_by_mac_addr.o \
./common/src/nx_nd_cache_interface_entries_delete.o \
./common/src/nx_nd_cache_slow_periodic_update.o \
./common/src/nx_packet_allocate.o \
./common/src/nx_packet_copy.o \
./common/src/nx_packet_data_adjust.o \
./common/src/nx_packet_data_append.o \
./common/src/nx_packet_data_extract_offset.o \
./common/src/nx_packet_data_retrieve.o \
./common/src/nx_packet_debug_info_get.o \
./common/src/nx_packet_length_get.o \
./common/src/nx_packet_pool_cleanup.o \
./common/src/nx_packet_pool_create.o \
./common/src/nx_packet_pool_delete.o \
./common/src/nx_packet_pool_info_get.o \
./common/src/nx_packet_pool_initialize.o \
./common/src/nx_packet_pool_low_watermark_set.o \
./common/src/nx_packet_release.o \
./common/src/nx_packet_transmit_release.o \
./common/src/nx_ram_network_driver.o \
./common/src/nx_rarp_disable.o \
./common/src/nx_rarp_enable.o \
./common/src/nx_rarp_info_get.o \
./common/src/nx_rarp_packet_deferred_receive.o \
./common/src/nx_rarp_packet_receive.o \
./common/src/nx_rarp_packet_send.o \
./common/src/nx_rarp_periodic_update.o \
./common/src/nx_rarp_queue_process.o \
./common/src/nx_system_initialize.o \
./common/src/nx_tcp_cleanup_deferred.o \
./common/src/nx_tcp_client_bind_cleanup.o \
./common/src/nx_tcp_client_socket_bind.o \
./common/src/nx_tcp_client_socket_connect.o \
./common/src/nx_tcp_client_socket_port_get.o \
./common/src/nx_tcp_client_socket_unbind.o \
./common/src/nx_tcp_connect_cleanup.o \
./common/src/nx_tcp_deferred_cleanup_check.o \
./common/src/nx_tcp_disconnect_cleanup.o \
./common/src/nx_tcp_enable.o \
./common/src/nx_tcp_fast_periodic_processing.o \
./common/src/nx_tcp_free_port_find.o \
./common/src/nx_tcp_info_get.o \
./common/src/nx_tcp_initialize.o \
./common/src/nx_tcp_mss_option_get.o \
./common/src/nx_tcp_no_connection_reset.o \
./common/src/nx_tcp_packet_process.o \
./common/src/nx_tcp_packet_receive.o \
./common/src/nx_tcp_packet_send_ack.o \
./common/src/nx_tcp_packet_send_control.o \
./common/src/nx_tcp_packet_send_fin.o \
./common/src/nx_tcp_packet_send_probe.o \
./common/src/nx_tcp_packet_send_rst.o \
./common/src/nx_tcp_packet_send_syn.o \
./common/src/nx_tcp_periodic_processing.o \
./common/src/nx_tcp_queue_process.o \
./common/src/nx_tcp_receive_cleanup.o \
./common/src/nx_tcp_server_socket_accept.o \
./common/src/nx_tcp_server_socket_listen.o \
./common/src/nx_tcp_server_socket_relisten.o \
./common/src/nx_tcp_server_socket_unaccept.o \
./common/src/nx_tcp_server_socket_unlisten.o \
./common/src/nx_tcp_socket_block_cleanup.o \
./common/src/nx_tcp_socket_bytes_available.o \
./common/src/nx_tcp_socket_connection_reset.o \
./common/src/nx_tcp_socket_create.o \
./common/src/nx_tcp_socket_delete.o \
./common/src/nx_tcp_socket_disconnect.o \
./common/src/nx_tcp_socket_disconnect_complete_notify.o \
./common/src/nx_tcp_socket_establish_notify.o \
./common/src/nx_tcp_socket_info_get.o \
./common/src/nx_tcp_socket_mss_get.o \
./common/src/nx_tcp_socket_mss_peer_get.o \
./common/src/nx_tcp_socket_mss_set.o \
./common/src/nx_tcp_socket_packet_process.o \
./common/src/nx_tcp_socket_peer_info_get.o \
./common/src/nx_tcp_socket_queue_depth_notify_set.o \
./common/src/nx_tcp_socket_receive.o \
./common/src/nx_tcp_socket_receive_notify.o \
./common/src/nx_tcp_socket_receive_queue_flush.o \
./common/src/nx_tcp_socket_receive_queue_max_set.o \
./common/src/nx_tcp_socket_retransmit.o \
./common/src/nx_tcp_socket_send.o \
./common/src/nx_tcp_socket_send_internal.o \
./common/src/nx_tcp_socket_state_ack_check.o \
./common/src/nx_tcp_socket_state_closing.o \
./common/src/nx_tcp_socket_state_data_check.o \
./common/src/nx_tcp_socket_state_established.o \
./common/src/nx_tcp_socket_state_fin_wait1.o \
./common/src/nx_tcp_socket_state_fin_wait2.o \
./common/src/nx_tcp_socket_state_last_ack.o \
./common/src/nx_tcp_socket_state_syn_received.o \
./common/src/nx_tcp_socket_state_syn_sent.o \
./common/src/nx_tcp_socket_state_transmit_check.o \
./common/src/nx_tcp_socket_state_wait.o \
./common/src/nx_tcp_socket_thread_resume.o \
./common/src/nx_tcp_socket_thread_suspend.o \
./common/src/nx_tcp_socket_timed_wait_callback.o \
./common/src/nx_tcp_socket_transmit_configure.o \
./common/src/nx_tcp_socket_transmit_queue_flush.o \
./common/src/nx_tcp_socket_window_update_notify_set.o \
./common/src/nx_tcp_transmit_cleanup.o \
./common/src/nx_tcp_window_scaling_option_get.o \
./common/src/nx_trace_event_insert.o \
./common/src/nx_trace_event_update.o \
./common/src/nx_trace_object_register.o \
./common/src/nx_trace_object_unregister.o \
./common/src/nx_udp_bind_cleanup.o \
./common/src/nx_udp_enable.o \
./common/src/nx_udp_free_port_find.o \
./common/src/nx_udp_info_get.o \
./common/src/nx_udp_packet_info_extract.o \
./common/src/nx_udp_packet_receive.o \
./common/src/nx_udp_receive_cleanup.o \
./common/src/nx_udp_socket_bind.o \
./common/src/nx_udp_socket_bytes_available.o \
./common/src/nx_udp_socket_checksum_disable.o \
./common/src/nx_udp_socket_checksum_enable.o \
./common/src/nx_udp_socket_create.o \
./common/src/nx_udp_socket_delete.o \
./common/src/nx_udp_socket_info_get.o \
./common/src/nx_udp_socket_port_get.o \
./common/src/nx_udp_socket_receive.o \
./common/src/nx_udp_socket_receive_notify.o \
./common/src/nx_udp_socket_send.o \
./common/src/nx_udp_socket_source_send.o \
./common/src/nx_udp_socket_unbind.o \
./common/src/nx_udp_source_extract.o \
./common/src/nx_utility.o \
./common/src/nxd_icmp_enable.o \
./common/src/nxd_icmp_ping.o \
./common/src/nxd_icmp_source_ping.o \
./common/src/nxd_icmpv6_ra_flag_callback_set.o \
./common/src/nxd_ip_raw_packet_send.o \
./common/src/nxd_ip_raw_packet_source_send.o \
./common/src/nxd_ipv6_address_change_notify.o \
./common/src/nxd_ipv6_address_delete.o \
./common/src/nxd_ipv6_address_get.o \
./common/src/nxd_ipv6_address_set.o \
./common/src/nxd_ipv6_default_router_add.o \
./common/src/nxd_ipv6_default_router_add_internal.o \
./common/src/nxd_ipv6_default_router_delete.o \
./common/src/nxd_ipv6_default_router_entry_get.o \
./common/src/nxd_ipv6_default_router_get.o \
./common/src/nxd_ipv6_default_router_number_of_entries_get.o \
./common/src/nxd_ipv6_default_router_table_init.o \
./common/src/nxd_ipv6_destination_table_find_next_hop.o \
./common/src/nxd_ipv6_disable.o \
./common/src/nxd_ipv6_enable.o \
./common/src/nxd_ipv6_find_default_router_from_address.o \
./common/src/nxd_ipv6_find_max_prefix_length.o \
./common/src/nxd_ipv6_interface_find.o \
./common/src/nxd_ipv6_multicast_interface_join.o \
./common/src/nxd_ipv6_multicast_interface_leave.o \
./common/src/nxd_ipv6_prefix_router_timer_tick.o \
./common/src/nxd_ipv6_raw_packet_send_internal.o \
./common/src/nxd_ipv6_router_lookup.o \
./common/src/nxd_ipv6_router_solicitation_check.o \
./common/src/nxd_ipv6_search_onlink.o \
./common/src/nxd_ipv6_stateless_address_autoconfig_disable.o \
./common/src/nxd_ipv6_stateless_address_autoconfig_enable.o \
./common/src/nxd_nd_cache_entry_delete.o \
./common/src/nxd_nd_cache_entry_set.o \
./common/src/nxd_nd_cache_hardware_address_find.o \
./common/src/nxd_nd_cache_invalidate.o \
./common/src/nxd_nd_cache_ip_address_find.o \
./common/src/nxd_tcp_client_socket_connect.o \
./common/src/nxd_tcp_socket_peer_info_get.o \
./common/src/nxd_udp_packet_info_extract.o \
./common/src/nxd_udp_socket_send.o \
./common/src/nxd_udp_socket_source_send.o \
./common/src/nxd_udp_source_extract.o \
./common/src/nxde_icmp_enable.o \
./common/src/nxde_icmp_ping.o \
./common/src/nxde_icmp_source_ping.o \
./common/src/nxde_icmpv6_ra_flag_callback_set.o \
./common/src/nxde_ip_raw_packet_send.o \
./common/src/nxde_ip_raw_packet_source_send.o \
./common/src/nxde_ipv6_address_change_notify.o \
./common/src/nxde_ipv6_address_delete.o \
./common/src/nxde_ipv6_address_get.o \
./common/src/nxde_ipv6_address_set.o \
./common/src/nxde_ipv6_default_router_add.o \
./common/src/nxde_ipv6_default_router_delete.o \
./common/src/nxde_ipv6_default_router_entry_get.o \
./common/src/nxde_ipv6_default_router_get.o \
./common/src/nxde_ipv6_default_router_number_of_entries_get.o \
./common/src/nxde_ipv6_disable.o \
./common/src/nxde_ipv6_enable.o \
./common/src/nxde_ipv6_multicast_interface_join.o \
./common/src/nxde_ipv6_multicast_interface_leave.o \
./common/src/nxde_ipv6_stateless_address_autoconfig_disable.o \
./common/src/nxde_ipv6_stateless_address_autoconfig_enable.o \
./common/src/nxde_nd_cache_entry_delete.o \
./common/src/nxde_nd_cache_entry_set.o \
./common/src/nxde_nd_cache_hardware_address_find.o \
./common/src/nxde_nd_cache_invalidate.o \
./common/src/nxde_nd_cache_ip_address_find.o \
./common/src/nxde_tcp_client_socket_connect.o \
./common/src/nxde_tcp_socket_peer_info_get.o \
./common/src/nxde_udp_packet_info_extract.o \
./common/src/nxde_udp_socket_send.o \
./common/src/nxde_udp_socket_source_send.o \
./common/src/nxde_udp_source_extract.o \
./common/src/nxe_arp_dynamic_entries_invalidate.o \
./common/src/nxe_arp_dynamic_entry_set.o \
./common/src/nxe_arp_enable.o \
./common/src/nxe_arp_entry_delete.o \
./common/src/nxe_arp_gratuitous_send.o \
./common/src/nxe_arp_hardware_address_find.o \
./common/src/nxe_arp_info_get.o \
./common/src/nxe_arp_ip_address_find.o \
./common/src/nxe_arp_static_entries_delete.o \
./common/src/nxe_arp_static_entry_create.o \
./common/src/nxe_arp_static_entry_delete.o \
./common/src/nxe_icmp_enable.o \
./common/src/nxe_icmp_info_get.o \
./common/src/nxe_icmp_ping.o \
./common/src/nxe_igmp_enable.o \
./common/src/nxe_igmp_info_get.o \
./common/src/nxe_igmp_loopback_disable.o \
./common/src/nxe_igmp_loopback_enable.o \
./common/src/nxe_igmp_multicast_interface_join.o \
./common/src/nxe_igmp_multicast_interface_leave.o \
./common/src/nxe_igmp_multicast_join.o \
./common/src/nxe_igmp_multicast_leave.o \
./common/src/nxe_ip_address_change_notify.o \
./common/src/nxe_ip_address_get.o \
./common/src/nxe_ip_address_set.o \
./common/src/nxe_ip_auxiliary_packet_pool_set.o \
./common/src/nxe_ip_create.o \
./common/src/nxe_ip_delete.o \
./common/src/nxe_ip_driver_direct_command.o \
./common/src/nxe_ip_driver_interface_direct_command.o \
./common/src/nxe_ip_forwarding_disable.o \
./common/src/nxe_ip_forwarding_enable.o \
./common/src/nxe_ip_fragment_disable.o \
./common/src/nxe_ip_fragment_enable.o \
./common/src/nxe_ip_gateway_address_clear.o \
./common/src/nxe_ip_gateway_address_get.o \
./common/src/nxe_ip_gateway_address_set.o \
./common/src/nxe_ip_info_get.o \
./common/src/nxe_ip_interface_address_get.o \
./common/src/nxe_ip_interface_address_mapping_configure.o \
./common/src/nxe_ip_interface_address_set.o \
./common/src/nxe_ip_interface_attach.o \
./common/src/nxe_ip_interface_capability_get.o \
./common/src/nxe_ip_interface_capability_set.o \
./common/src/nxe_ip_interface_detach.o \
./common/src/nxe_ip_interface_info_get.o \
./common/src/nxe_ip_interface_mtu_set.o \
./common/src/nxe_ip_interface_physical_address_get.o \
./common/src/nxe_ip_interface_physical_address_set.o \
./common/src/nxe_ip_interface_status_check.o \
./common/src/nxe_ip_link_status_change_notify_set.o \
./common/src/nxe_ip_max_payload_size_find.o \
./common/src/nxe_ip_raw_packet_disable.o \
./common/src/nxe_ip_raw_packet_enable.o \
./common/src/nxe_ip_raw_packet_filter_set.o \
./common/src/nxe_ip_raw_packet_receive.o \
./common/src/nxe_ip_raw_packet_send.o \
./common/src/nxe_ip_raw_packet_source_send.o \
./common/src/nxe_ip_raw_receive_queue_max_set.o \
./common/src/nxe_ip_static_route_add.o \
./common/src/nxe_ip_static_route_delete.o \
./common/src/nxe_ip_status_check.o \
./common/src/nxe_ipv4_multicast_interface_join.o \
./common/src/nxe_ipv4_multicast_interface_leave.o \
./common/src/nxe_packet_allocate.o \
./common/src/nxe_packet_copy.o \
./common/src/nxe_packet_data_append.o \
./common/src/nxe_packet_data_extract_offset.o \
./common/src/nxe_packet_data_retrieve.o \
./common/src/nxe_packet_length_get.o \
./common/src/nxe_packet_pool_create.o \
./common/src/nxe_packet_pool_delete.o \
./common/src/nxe_packet_pool_info_get.o \
./common/src/nxe_packet_pool_low_watermark_set.o \
./common/src/nxe_packet_release.o \
./common/src/nxe_packet_transmit_release.o \
./common/src/nxe_rarp_disable.o \
./common/src/nxe_rarp_enable.o \
./common/src/nxe_rarp_info_get.o \
./common/src/nxe_tcp_client_socket_bind.o \
./common/src/nxe_tcp_client_socket_connect.o \
./common/src/nxe_tcp_client_socket_port_get.o \
./common/src/nxe_tcp_client_socket_unbind.o \
./common/src/nxe_tcp_enable.o \
./common/src/nxe_tcp_free_port_find.o \
./common/src/nxe_tcp_info_get.o \
./common/src/nxe_tcp_server_socket_accept.o \
./common/src/nxe_tcp_server_socket_listen.o \
./common/src/nxe_tcp_server_socket_relisten.o \
./common/src/nxe_tcp_server_socket_unaccept.o \
./common/src/nxe_tcp_server_socket_unlisten.o \
./common/src/nxe_tcp_socket_bytes_available.o \
./common/src/nxe_tcp_socket_create.o \
./common/src/nxe_tcp_socket_delete.o \
./common/src/nxe_tcp_socket_disconnect.o \
./common/src/nxe_tcp_socket_disconnect_complete_notify.o \
./common/src/nxe_tcp_socket_establish_notify.o \
./common/src/nxe_tcp_socket_info_get.o \
./common/src/nxe_tcp_socket_mss_get.o \
./common/src/nxe_tcp_socket_mss_peer_get.o \
./common/src/nxe_tcp_socket_mss_set.o \
./common/src/nxe_tcp_socket_peer_info_get.o \
./common/src/nxe_tcp_socket_queue_depth_notify_set.o \
./common/src/nxe_tcp_socket_receive.o \
./common/src/nxe_tcp_socket_receive_notify.o \
./common/src/nxe_tcp_socket_receive_queue_max_set.o \
./common/src/nxe_tcp_socket_send.o \
./common/src/nxe_tcp_socket_state_wait.o \
./common/src/nxe_tcp_socket_timed_wait_callback.o \
./common/src/nxe_tcp_socket_transmit_configure.o \
./common/src/nxe_tcp_socket_window_update_notify_set.o \
./common/src/nxe_udp_enable.o \
./common/src/nxe_udp_free_port_find.o \
./common/src/nxe_udp_info_get.o \
./common/src/nxe_udp_packet_info_extract.o \
./common/src/nxe_udp_socket_bind.o \
./common/src/nxe_udp_socket_bytes_available.o \
./common/src/nxe_udp_socket_checksum_disable.o \
./common/src/nxe_udp_socket_checksum_enable.o \
./common/src/nxe_udp_socket_create.o \
./common/src/nxe_udp_socket_delete.o \
./common/src/nxe_udp_socket_info_get.o \
./common/src/nxe_udp_socket_port_get.o \
./common/src/nxe_udp_socket_receive.o \
./common/src/nxe_udp_socket_receive_notify.o \
./common/src/nxe_udp_socket_send.o \
./common/src/nxe_udp_socket_source_send.o \
./common/src/nxe_udp_socket_unbind.o \
./common/src/nxe_udp_source_extract.o 


# Each subdirectory must supply rules for building sources it contributes
common/src/%.o: ../common/src/%.c
	arm-none-eabi-gcc -mcpu=cortex-a9 -march=armv7-a -marm -mlittle-endian -mfloat-abi=hard -mfpu=vfpv3-d16 -O3 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wnull-dereference -g -Wstack-usage=2000 -I../../filex/ports/cortex_a9/gnu/inc -I../../filex/common/inc -I../../threadx/common/inc -I../../rz_bsp/azure/ports/cortex_a9/gnu/inc -I../../netxduo/common/inc -I../../netxduo/crypto_libraries/inc -I../../netxduo/nx_secure/ports -I../../netxduo/nx_secure/inc -I../../netxduo/addons/azure_iot -I../../netxduo/addons/azure_iot/azure-sdk-for-c/sdk/inc -I../../netxduo/addons/azure_iot/azure_iot_security_module/iot-security-module-core/inc -I../../netxduo/addons/azure_iot/azure_iot_security_module/inc -I../../netxduo/addons/azure_iot/azure_iot_security_module -I../../netxduo/addons/azure_iot/azure_iot_security_module/iot-security-module-core/deps/flatcc/src/runtime -I../../netxduo/addons/azure_iot/azure_iot_security_module/iot-security-module-core/deps/flatcc/include -I../../netxduo/addons/cloud -I../../netxduo/addons/mqtt -I../../netxduo/addons/dns -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"

