################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../common/usbx_host_controllers/ux_hcd_rz_asynch_queue_process.c \
../common/usbx_host_controllers/ux_hcd_rz_asynch_queue_process_bemp.c \
../common/usbx_host_controllers/ux_hcd_rz_asynch_queue_process_brdy.c \
../common/usbx_host_controllers/ux_hcd_rz_asynch_queue_process_nrdy.c \
../common/usbx_host_controllers/ux_hcd_rz_asynch_queue_process_sign.c \
../common/usbx_host_controllers/ux_hcd_rz_asynch_schedule.c \
../common/usbx_host_controllers/ux_hcd_rz_asynchronous_endpoint_create.c \
../common/usbx_host_controllers/ux_hcd_rz_asynchronous_endpoint_destroy.c \
../common/usbx_host_controllers/ux_hcd_rz_buffer_empty_interrupt.c \
../common/usbx_host_controllers/ux_hcd_rz_buffer_notready_interrupt.c \
../common/usbx_host_controllers/ux_hcd_rz_buffer_read.c \
../common/usbx_host_controllers/ux_hcd_rz_buffer_ready_interrupt.c \
../common/usbx_host_controllers/ux_hcd_rz_buffer_write.c \
../common/usbx_host_controllers/ux_hcd_rz_bulk_endpoint_create.c \
../common/usbx_host_controllers/ux_hcd_rz_bulk_int_td_add.c \
../common/usbx_host_controllers/ux_hcd_rz_control_endpoint_create.c \
../common/usbx_host_controllers/ux_hcd_rz_control_td_add.c \
../common/usbx_host_controllers/ux_hcd_rz_controller_disable.c \
../common/usbx_host_controllers/ux_hcd_rz_current_endpoint_change.c \
../common/usbx_host_controllers/ux_hcd_rz_data_buffer_size.c \
../common/usbx_host_controllers/ux_hcd_rz_dma_register_clear.c \
../common/usbx_host_controllers/ux_hcd_rz_dma_register_read.c \
../common/usbx_host_controllers/ux_hcd_rz_dma_register_set.c \
../common/usbx_host_controllers/ux_hcd_rz_dma_register_write.c \
../common/usbx_host_controllers/ux_hcd_rz_dma_rx_interrupt_handler.c \
../common/usbx_host_controllers/ux_hcd_rz_dma_tx_interrupt_handler.c \
../common/usbx_host_controllers/ux_hcd_rz_ed_obtain.c \
../common/usbx_host_controllers/ux_hcd_rz_ed_td_clean.c \
../common/usbx_host_controllers/ux_hcd_rz_endpoint_nak_set.c \
../common/usbx_host_controllers/ux_hcd_rz_endpoint_reset.c \
../common/usbx_host_controllers/ux_hcd_rz_entry.c \
../common/usbx_host_controllers/ux_hcd_rz_fifo_port_change.c \
../common/usbx_host_controllers/ux_hcd_rz_fifo_read.c \
../common/usbx_host_controllers/ux_hcd_rz_fifoc_write.c \
../common/usbx_host_controllers/ux_hcd_rz_fifod_write.c \
../common/usbx_host_controllers/ux_hcd_rz_frame_number_get.c \
../common/usbx_host_controllers/ux_hcd_rz_frame_number_set.c \
../common/usbx_host_controllers/ux_hcd_rz_initialize.c \
../common/usbx_host_controllers/ux_hcd_rz_interrupt_endpoint_create.c \
../common/usbx_host_controllers/ux_hcd_rz_interrupt_handler.c \
../common/usbx_host_controllers/ux_hcd_rz_iso_queue_process.c \
../common/usbx_host_controllers/ux_hcd_rz_iso_schedule.c \
../common/usbx_host_controllers/ux_hcd_rz_isochronous_endpoint_create.c \
../common/usbx_host_controllers/ux_hcd_rz_isochronous_td_obtain.c \
../common/usbx_host_controllers/ux_hcd_rz_least_traffic_list_get.c \
../common/usbx_host_controllers/ux_hcd_rz_low_level_setup.c \
../common/usbx_host_controllers/ux_hcd_rz_periodic_endpoint_destroy.c \
../common/usbx_host_controllers/ux_hcd_rz_periodic_schedule.c \
../common/usbx_host_controllers/ux_hcd_rz_periodic_tree_create.c \
../common/usbx_host_controllers/ux_hcd_rz_port_disable.c \
../common/usbx_host_controllers/ux_hcd_rz_port_enable.c \
../common/usbx_host_controllers/ux_hcd_rz_port_reset.c \
../common/usbx_host_controllers/ux_hcd_rz_port_resume.c \
../common/usbx_host_controllers/ux_hcd_rz_port_status_get.c \
../common/usbx_host_controllers/ux_hcd_rz_port_suspend.c \
../common/usbx_host_controllers/ux_hcd_rz_power_down_port.c \
../common/usbx_host_controllers/ux_hcd_rz_power_on_port.c \
../common/usbx_host_controllers/ux_hcd_rz_power_root_hubs.c \
../common/usbx_host_controllers/ux_hcd_rz_register_clear.c \
../common/usbx_host_controllers/ux_hcd_rz_register_read.c \
../common/usbx_host_controllers/ux_hcd_rz_register_set.c \
../common/usbx_host_controllers/ux_hcd_rz_register_write.c \
../common/usbx_host_controllers/ux_hcd_rz_regular_td_obtain.c \
../common/usbx_host_controllers/ux_hcd_rz_request_bulk_transfer.c \
../common/usbx_host_controllers/ux_hcd_rz_request_control_transfer.c \
../common/usbx_host_controllers/ux_hcd_rz_request_interupt_transfer.c \
../common/usbx_host_controllers/ux_hcd_rz_request_isochronous_transfer.c \
../common/usbx_host_controllers/ux_hcd_rz_request_transfer.c \
../common/usbx_host_controllers/ux_hcd_rz_td_add.c \
../common/usbx_host_controllers/ux_hcd_rz_transfer_abort.c 

C_DEPS += \
./common/usbx_host_controllers/ux_hcd_rz_asynch_queue_process.d \
./common/usbx_host_controllers/ux_hcd_rz_asynch_queue_process_bemp.d \
./common/usbx_host_controllers/ux_hcd_rz_asynch_queue_process_brdy.d \
./common/usbx_host_controllers/ux_hcd_rz_asynch_queue_process_nrdy.d \
./common/usbx_host_controllers/ux_hcd_rz_asynch_queue_process_sign.d \
./common/usbx_host_controllers/ux_hcd_rz_asynch_schedule.d \
./common/usbx_host_controllers/ux_hcd_rz_asynchronous_endpoint_create.d \
./common/usbx_host_controllers/ux_hcd_rz_asynchronous_endpoint_destroy.d \
./common/usbx_host_controllers/ux_hcd_rz_buffer_empty_interrupt.d \
./common/usbx_host_controllers/ux_hcd_rz_buffer_notready_interrupt.d \
./common/usbx_host_controllers/ux_hcd_rz_buffer_read.d \
./common/usbx_host_controllers/ux_hcd_rz_buffer_ready_interrupt.d \
./common/usbx_host_controllers/ux_hcd_rz_buffer_write.d \
./common/usbx_host_controllers/ux_hcd_rz_bulk_endpoint_create.d \
./common/usbx_host_controllers/ux_hcd_rz_bulk_int_td_add.d \
./common/usbx_host_controllers/ux_hcd_rz_control_endpoint_create.d \
./common/usbx_host_controllers/ux_hcd_rz_control_td_add.d \
./common/usbx_host_controllers/ux_hcd_rz_controller_disable.d \
./common/usbx_host_controllers/ux_hcd_rz_current_endpoint_change.d \
./common/usbx_host_controllers/ux_hcd_rz_data_buffer_size.d \
./common/usbx_host_controllers/ux_hcd_rz_dma_register_clear.d \
./common/usbx_host_controllers/ux_hcd_rz_dma_register_read.d \
./common/usbx_host_controllers/ux_hcd_rz_dma_register_set.d \
./common/usbx_host_controllers/ux_hcd_rz_dma_register_write.d \
./common/usbx_host_controllers/ux_hcd_rz_dma_rx_interrupt_handler.d \
./common/usbx_host_controllers/ux_hcd_rz_dma_tx_interrupt_handler.d \
./common/usbx_host_controllers/ux_hcd_rz_ed_obtain.d \
./common/usbx_host_controllers/ux_hcd_rz_ed_td_clean.d \
./common/usbx_host_controllers/ux_hcd_rz_endpoint_nak_set.d \
./common/usbx_host_controllers/ux_hcd_rz_endpoint_reset.d \
./common/usbx_host_controllers/ux_hcd_rz_entry.d \
./common/usbx_host_controllers/ux_hcd_rz_fifo_port_change.d \
./common/usbx_host_controllers/ux_hcd_rz_fifo_read.d \
./common/usbx_host_controllers/ux_hcd_rz_fifoc_write.d \
./common/usbx_host_controllers/ux_hcd_rz_fifod_write.d \
./common/usbx_host_controllers/ux_hcd_rz_frame_number_get.d \
./common/usbx_host_controllers/ux_hcd_rz_frame_number_set.d \
./common/usbx_host_controllers/ux_hcd_rz_initialize.d \
./common/usbx_host_controllers/ux_hcd_rz_interrupt_endpoint_create.d \
./common/usbx_host_controllers/ux_hcd_rz_interrupt_handler.d \
./common/usbx_host_controllers/ux_hcd_rz_iso_queue_process.d \
./common/usbx_host_controllers/ux_hcd_rz_iso_schedule.d \
./common/usbx_host_controllers/ux_hcd_rz_isochronous_endpoint_create.d \
./common/usbx_host_controllers/ux_hcd_rz_isochronous_td_obtain.d \
./common/usbx_host_controllers/ux_hcd_rz_least_traffic_list_get.d \
./common/usbx_host_controllers/ux_hcd_rz_low_level_setup.d \
./common/usbx_host_controllers/ux_hcd_rz_periodic_endpoint_destroy.d \
./common/usbx_host_controllers/ux_hcd_rz_periodic_schedule.d \
./common/usbx_host_controllers/ux_hcd_rz_periodic_tree_create.d \
./common/usbx_host_controllers/ux_hcd_rz_port_disable.d \
./common/usbx_host_controllers/ux_hcd_rz_port_enable.d \
./common/usbx_host_controllers/ux_hcd_rz_port_reset.d \
./common/usbx_host_controllers/ux_hcd_rz_port_resume.d \
./common/usbx_host_controllers/ux_hcd_rz_port_status_get.d \
./common/usbx_host_controllers/ux_hcd_rz_port_suspend.d \
./common/usbx_host_controllers/ux_hcd_rz_power_down_port.d \
./common/usbx_host_controllers/ux_hcd_rz_power_on_port.d \
./common/usbx_host_controllers/ux_hcd_rz_power_root_hubs.d \
./common/usbx_host_controllers/ux_hcd_rz_register_clear.d \
./common/usbx_host_controllers/ux_hcd_rz_register_read.d \
./common/usbx_host_controllers/ux_hcd_rz_register_set.d \
./common/usbx_host_controllers/ux_hcd_rz_register_write.d \
./common/usbx_host_controllers/ux_hcd_rz_regular_td_obtain.d \
./common/usbx_host_controllers/ux_hcd_rz_request_bulk_transfer.d \
./common/usbx_host_controllers/ux_hcd_rz_request_control_transfer.d \
./common/usbx_host_controllers/ux_hcd_rz_request_interupt_transfer.d \
./common/usbx_host_controllers/ux_hcd_rz_request_isochronous_transfer.d \
./common/usbx_host_controllers/ux_hcd_rz_request_transfer.d \
./common/usbx_host_controllers/ux_hcd_rz_td_add.d \
./common/usbx_host_controllers/ux_hcd_rz_transfer_abort.d 

OBJS += \
./common/usbx_host_controllers/ux_hcd_rz_asynch_queue_process.o \
./common/usbx_host_controllers/ux_hcd_rz_asynch_queue_process_bemp.o \
./common/usbx_host_controllers/ux_hcd_rz_asynch_queue_process_brdy.o \
./common/usbx_host_controllers/ux_hcd_rz_asynch_queue_process_nrdy.o \
./common/usbx_host_controllers/ux_hcd_rz_asynch_queue_process_sign.o \
./common/usbx_host_controllers/ux_hcd_rz_asynch_schedule.o \
./common/usbx_host_controllers/ux_hcd_rz_asynchronous_endpoint_create.o \
./common/usbx_host_controllers/ux_hcd_rz_asynchronous_endpoint_destroy.o \
./common/usbx_host_controllers/ux_hcd_rz_buffer_empty_interrupt.o \
./common/usbx_host_controllers/ux_hcd_rz_buffer_notready_interrupt.o \
./common/usbx_host_controllers/ux_hcd_rz_buffer_read.o \
./common/usbx_host_controllers/ux_hcd_rz_buffer_ready_interrupt.o \
./common/usbx_host_controllers/ux_hcd_rz_buffer_write.o \
./common/usbx_host_controllers/ux_hcd_rz_bulk_endpoint_create.o \
./common/usbx_host_controllers/ux_hcd_rz_bulk_int_td_add.o \
./common/usbx_host_controllers/ux_hcd_rz_control_endpoint_create.o \
./common/usbx_host_controllers/ux_hcd_rz_control_td_add.o \
./common/usbx_host_controllers/ux_hcd_rz_controller_disable.o \
./common/usbx_host_controllers/ux_hcd_rz_current_endpoint_change.o \
./common/usbx_host_controllers/ux_hcd_rz_data_buffer_size.o \
./common/usbx_host_controllers/ux_hcd_rz_dma_register_clear.o \
./common/usbx_host_controllers/ux_hcd_rz_dma_register_read.o \
./common/usbx_host_controllers/ux_hcd_rz_dma_register_set.o \
./common/usbx_host_controllers/ux_hcd_rz_dma_register_write.o \
./common/usbx_host_controllers/ux_hcd_rz_dma_rx_interrupt_handler.o \
./common/usbx_host_controllers/ux_hcd_rz_dma_tx_interrupt_handler.o \
./common/usbx_host_controllers/ux_hcd_rz_ed_obtain.o \
./common/usbx_host_controllers/ux_hcd_rz_ed_td_clean.o \
./common/usbx_host_controllers/ux_hcd_rz_endpoint_nak_set.o \
./common/usbx_host_controllers/ux_hcd_rz_endpoint_reset.o \
./common/usbx_host_controllers/ux_hcd_rz_entry.o \
./common/usbx_host_controllers/ux_hcd_rz_fifo_port_change.o \
./common/usbx_host_controllers/ux_hcd_rz_fifo_read.o \
./common/usbx_host_controllers/ux_hcd_rz_fifoc_write.o \
./common/usbx_host_controllers/ux_hcd_rz_fifod_write.o \
./common/usbx_host_controllers/ux_hcd_rz_frame_number_get.o \
./common/usbx_host_controllers/ux_hcd_rz_frame_number_set.o \
./common/usbx_host_controllers/ux_hcd_rz_initialize.o \
./common/usbx_host_controllers/ux_hcd_rz_interrupt_endpoint_create.o \
./common/usbx_host_controllers/ux_hcd_rz_interrupt_handler.o \
./common/usbx_host_controllers/ux_hcd_rz_iso_queue_process.o \
./common/usbx_host_controllers/ux_hcd_rz_iso_schedule.o \
./common/usbx_host_controllers/ux_hcd_rz_isochronous_endpoint_create.o \
./common/usbx_host_controllers/ux_hcd_rz_isochronous_td_obtain.o \
./common/usbx_host_controllers/ux_hcd_rz_least_traffic_list_get.o \
./common/usbx_host_controllers/ux_hcd_rz_low_level_setup.o \
./common/usbx_host_controllers/ux_hcd_rz_periodic_endpoint_destroy.o \
./common/usbx_host_controllers/ux_hcd_rz_periodic_schedule.o \
./common/usbx_host_controllers/ux_hcd_rz_periodic_tree_create.o \
./common/usbx_host_controllers/ux_hcd_rz_port_disable.o \
./common/usbx_host_controllers/ux_hcd_rz_port_enable.o \
./common/usbx_host_controllers/ux_hcd_rz_port_reset.o \
./common/usbx_host_controllers/ux_hcd_rz_port_resume.o \
./common/usbx_host_controllers/ux_hcd_rz_port_status_get.o \
./common/usbx_host_controllers/ux_hcd_rz_port_suspend.o \
./common/usbx_host_controllers/ux_hcd_rz_power_down_port.o \
./common/usbx_host_controllers/ux_hcd_rz_power_on_port.o \
./common/usbx_host_controllers/ux_hcd_rz_power_root_hubs.o \
./common/usbx_host_controllers/ux_hcd_rz_register_clear.o \
./common/usbx_host_controllers/ux_hcd_rz_register_read.o \
./common/usbx_host_controllers/ux_hcd_rz_register_set.o \
./common/usbx_host_controllers/ux_hcd_rz_register_write.o \
./common/usbx_host_controllers/ux_hcd_rz_regular_td_obtain.o \
./common/usbx_host_controllers/ux_hcd_rz_request_bulk_transfer.o \
./common/usbx_host_controllers/ux_hcd_rz_request_control_transfer.o \
./common/usbx_host_controllers/ux_hcd_rz_request_interupt_transfer.o \
./common/usbx_host_controllers/ux_hcd_rz_request_isochronous_transfer.o \
./common/usbx_host_controllers/ux_hcd_rz_request_transfer.o \
./common/usbx_host_controllers/ux_hcd_rz_td_add.o \
./common/usbx_host_controllers/ux_hcd_rz_transfer_abort.o 


# Each subdirectory must supply rules for building sources it contributes
common/usbx_host_controllers/%.o: ../common/usbx_host_controllers/%.c
	arm-none-eabi-gcc -mcpu=cortex-a9 -march=armv7-a -marm -mlittle-endian -mfloat-abi=hard -mfpu=vfpv3-d16 -O3 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wnull-dereference -g -Wstack-usage=1000 -I"C:\workspace\RZA1\Azure\rza1h_azure_gcc\filex\common\inc" -I"C:\workspace\RZA1\Azure\rza1h_azure_gcc\rz_bsp\azure\ports\cortex_a9\gnu\inc" -I"C:\workspace\RZA1\Azure\rza1h_azure_gcc\netxduo\common\inc" -I"C:\workspace\RZA1\Azure\rza1h_azure_gcc\usbx\common\core\inc" -I"C:\workspace\RZA1\Azure\rza1h_azure_gcc\threadx\common\inc" -I"C:\workspace\RZA1\Azure\rza1h_azure_gcc\usbx\common\usbx_host_classes\inc" -I"C:\workspace\RZA1\Azure\rza1h_azure_gcc\usbx\common\usbx_device_classes\inc" -I"C:\workspace\RZA1\Azure\rza1h_azure_gcc\usbx\common\usbx_device_controllers" -I"C:\workspace\RZA1\Azure\rza1h_azure_gcc\usbx\common\usbx_host_controllers" -I"C:\workspace\RZA1\Azure\rza1h_azure_gcc\usbx\common\usbx_network\inc" -I"C:\workspace\RZA1\Azure\rza1h_azure_gcc\usbx\common\usbx_pictbridge\inc" -I"C:\workspace\RZA1\Azure\rza1h_azure_gcc\rz_bsp\src\arm\cmsis\inc" -I"C:\workspace\RZA1\Azure\rza1h_azure_gcc\rz_bsp\src\renesas\compiler\inc" -I"C:\workspace\RZA1\Azure\rza1h_azure_gcc\rz_bsp\src\renesas\configuration" -I"C:\workspace\RZA1\Azure\rza1h_azure_gcc\rz_bsp\src\renesas\configuration\os_abstraction\inc" -I"C:\workspace\RZA1\Azure\rza1h_azure_gcc\rz_bsp\src\renesas\configuration\sc\inc" -I"C:\workspace\RZA1\Azure\rza1h_azure_gcc\rz_bsp\src\renesas\application\inc" -I"C:\workspace\RZA1\Azure\rza1h_azure_gcc\rz_bsp\src\renesas\application\graphics\inc" -I"C:\workspace\RZA1\Azure\rza1h_azure_gcc\rz_bsp\src\renesas\application\console\inc" -I"C:\workspace\RZA1\Azure\rza1h_azure_gcc\rz_bsp\src\renesas\application\system\inc" -I"C:\workspace\RZA1\Azure\rza1h_azure_gcc\rz_bsp\src\renesas\application\system\iodefines" -I"C:\workspace\RZA1\Azure\rza1h_azure_gcc\rz_bsp\src\renesas\application\system\iobitmasks" -I"C:\workspace\RZA1\Azure\rza1h_azure_gcc\rz_bsp\src\renesas\drivers\adc\inc" -I"C:\workspace\RZA1\Azure\rza1h_azure_gcc\rz_bsp\src\renesas\drivers\intc\inc" -I"C:\workspace\RZA1\Azure\rza1h_azure_gcc\rz_bsp\src\renesas\drivers\ostm\inc" -I"C:\workspace\RZA1\Azure\rza1h_azure_gcc\rz_bsp\src\renesas\drivers\r_cache\inc" -I"C:\workspace\RZA1\Azure\rza1h_azure_gcc\rz_bsp\src\renesas\drivers\r_ceu\inc" -I"C:\workspace\RZA1\Azure\rza1h_azure_gcc\rz_bsp\src\renesas\drivers\r_dmac\inc" -I"C:\workspace\RZA1\Azure\rza1h_azure_gcc\rz_bsp\src\renesas\drivers\r_eeprom\inc" -I"C:\workspace\RZA1\Azure\rza1h_azure_gcc\rz_bsp\src\renesas\drivers\r_i2c\inc" -I"C:\workspace\RZA1\Azure\rza1h_azure_gcc\rz_bsp\src\renesas\drivers\r_jcu\inc" -I"C:\workspace\RZA1\Azure\rza1h_azure_gcc\rz_bsp\src\renesas\drivers\r_l2cc" -I"C:\workspace\RZA1\Azure\rza1h_azure_gcc\rz_bsp\src\renesas\drivers\r_led\inc" -I"C:\workspace\RZA1\Azure\rza1h_azure_gcc\rz_bsp\src\renesas\drivers\r_rspi\inc" -I"C:\workspace\RZA1\Azure\rza1h_azure_gcc\rz_bsp\src\renesas\drivers\r_rtc\inc" -I"C:\workspace\RZA1\Azure\rza1h_azure_gcc\rz_bsp\src\renesas\drivers\r_sci\inc" -I"C:\workspace\RZA1\Azure\rza1h_azure_gcc\rz_bsp\src\renesas\drivers\r_ssif\inc" -I"C:\workspace\RZA1\Azure\rza1h_azure_gcc\rz_bsp\src\renesas\drivers\r_switch\inc" -I"C:\workspace\RZA1\Azure\rza1h_azure_gcc\rz_bsp\src\renesas\drivers\r_vdc_vdec\inc" -I"C:\workspace\RZA1\Azure\rza1h_azure_gcc\rz_bsp\src\renesas\drivers\r_wdt\inc" -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"

