################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../nx_secure/src/nx_secure_crypto_method_self_test_3des.c \
../nx_secure/src/nx_secure_crypto_method_self_test_aes.c \
../nx_secure/src/nx_secure_crypto_method_self_test_des.c \
../nx_secure/src/nx_secure_crypto_method_self_test_hmac_md5.c \
../nx_secure/src/nx_secure_crypto_method_self_test_hmac_sha.c \
../nx_secure/src/nx_secure_crypto_method_self_test_md5.c \
../nx_secure/src/nx_secure_crypto_method_self_test_prf.c \
../nx_secure/src/nx_secure_crypto_method_self_test_rsa.c \
../nx_secure/src/nx_secure_crypto_method_self_test_sha.c \
../nx_secure/src/nx_secure_crypto_rng_self_test.c \
../nx_secure/src/nx_secure_crypto_table_self_test.c \
../nx_secure/src/nx_secure_dtls_allocate_handshake_packet.c \
../nx_secure/src/nx_secure_dtls_client_handshake.c \
../nx_secure/src/nx_secure_dtls_client_protocol_version_override.c \
../nx_secure/src/nx_secure_dtls_client_session_start.c \
../nx_secure/src/nx_secure_dtls_ecc_initialize.c \
../nx_secure/src/nx_secure_dtls_hash_record.c \
../nx_secure/src/nx_secure_dtls_initialize.c \
../nx_secure/src/nx_secure_dtls_packet_allocate.c \
../nx_secure/src/nx_secure_dtls_process_clienthello.c \
../nx_secure/src/nx_secure_dtls_process_handshake_header.c \
../nx_secure/src/nx_secure_dtls_process_header.c \
../nx_secure/src/nx_secure_dtls_process_helloverifyrequest.c \
../nx_secure/src/nx_secure_dtls_process_record.c \
../nx_secure/src/nx_secure_dtls_psk_add.c \
../nx_secure/src/nx_secure_dtls_receive_callback.c \
../nx_secure/src/nx_secure_dtls_retransmit.c \
../nx_secure/src/nx_secure_dtls_retransmit_queue_flush.c \
../nx_secure/src/nx_secure_dtls_send_clienthello.c \
../nx_secure/src/nx_secure_dtls_send_handshake_record.c \
../nx_secure/src/nx_secure_dtls_send_helloverifyrequest.c \
../nx_secure/src/nx_secure_dtls_send_record.c \
../nx_secure/src/nx_secure_dtls_send_serverhello.c \
../nx_secure/src/nx_secure_dtls_server_create.c \
../nx_secure/src/nx_secure_dtls_server_delete.c \
../nx_secure/src/nx_secure_dtls_server_ecc_initialize.c \
../nx_secure/src/nx_secure_dtls_server_handshake.c \
../nx_secure/src/nx_secure_dtls_server_local_certificate_add.c \
../nx_secure/src/nx_secure_dtls_server_local_certificate_remove.c \
../nx_secure/src/nx_secure_dtls_server_notify_set.c \
../nx_secure/src/nx_secure_dtls_server_protocol_version_override.c \
../nx_secure/src/nx_secure_dtls_server_psk_add.c \
../nx_secure/src/nx_secure_dtls_server_session_send.c \
../nx_secure/src/nx_secure_dtls_server_session_start.c \
../nx_secure/src/nx_secure_dtls_server_start.c \
../nx_secure/src/nx_secure_dtls_server_stop.c \
../nx_secure/src/nx_secure_dtls_server_trusted_certificate_add.c \
../nx_secure/src/nx_secure_dtls_server_trusted_certificate_remove.c \
../nx_secure/src/nx_secure_dtls_server_x509_client_verify_configure.c \
../nx_secure/src/nx_secure_dtls_server_x509_client_verify_disable.c \
../nx_secure/src/nx_secure_dtls_session_cache.c \
../nx_secure/src/nx_secure_dtls_session_client_info_get.c \
../nx_secure/src/nx_secure_dtls_session_create.c \
../nx_secure/src/nx_secure_dtls_session_delete.c \
../nx_secure/src/nx_secure_dtls_session_end.c \
../nx_secure/src/nx_secure_dtls_session_local_certificate_add.c \
../nx_secure/src/nx_secure_dtls_session_local_certificate_remove.c \
../nx_secure/src/nx_secure_dtls_session_receive.c \
../nx_secure/src/nx_secure_dtls_session_reset.c \
../nx_secure/src/nx_secure_dtls_session_send.c \
../nx_secure/src/nx_secure_dtls_session_start.c \
../nx_secure/src/nx_secure_dtls_session_trusted_certificate_add.c \
../nx_secure/src/nx_secure_dtls_session_trusted_certificate_remove.c \
../nx_secure/src/nx_secure_dtls_verify_mac.c \
../nx_secure/src/nx_secure_module_hash_compute.c \
../nx_secure/src/nx_secure_tls_1_3_client_handshake.c \
../nx_secure/src/nx_secure_tls_1_3_crypto_init.c \
../nx_secure/src/nx_secure_tls_1_3_finished_hash_generate.c \
../nx_secure/src/nx_secure_tls_1_3_generate_keys.c \
../nx_secure/src/nx_secure_tls_1_3_server_handshake.c \
../nx_secure/src/nx_secure_tls_1_3_session_keys_set.c \
../nx_secure/src/nx_secure_tls_1_3_transcript_hash_save.c \
../nx_secure/src/nx_secure_tls_active_certificate_set.c \
../nx_secure/src/nx_secure_tls_allocate_handshake_packet.c \
../nx_secure/src/nx_secure_tls_check_protocol_version.c \
../nx_secure/src/nx_secure_tls_ciphersuite_lookup.c \
../nx_secure/src/nx_secure_tls_client_handshake.c \
../nx_secure/src/nx_secure_tls_client_psk_set.c \
../nx_secure/src/nx_secure_tls_ecc_generate_keys.c \
../nx_secure/src/nx_secure_tls_ecc_initialize.c \
../nx_secure/src/nx_secure_tls_find_curve_method.c \
../nx_secure/src/nx_secure_tls_finished_hash_generate.c \
../nx_secure/src/nx_secure_tls_generate_keys.c \
../nx_secure/src/nx_secure_tls_generate_premaster_secret.c \
../nx_secure/src/nx_secure_tls_handshake_hash_init.c \
../nx_secure/src/nx_secure_tls_handshake_hash_update.c \
../nx_secure/src/nx_secure_tls_handshake_process.c \
../nx_secure/src/nx_secure_tls_hash_record.c \
../nx_secure/src/nx_secure_tls_initialize.c \
../nx_secure/src/nx_secure_tls_key_material_init.c \
../nx_secure/src/nx_secure_tls_local_certificate_add.c \
../nx_secure/src/nx_secure_tls_local_certificate_find.c \
../nx_secure/src/nx_secure_tls_local_certificate_remove.c \
../nx_secure/src/nx_secure_tls_map_error_to_alert.c \
../nx_secure/src/nx_secure_tls_metadata_size_calculate.c \
../nx_secure/src/nx_secure_tls_newest_supported_version.c \
../nx_secure/src/nx_secure_tls_packet_allocate.c \
../nx_secure/src/nx_secure_tls_packet_release.c \
../nx_secure/src/nx_secure_tls_process_certificate_request.c \
../nx_secure/src/nx_secure_tls_process_certificate_verify.c \
../nx_secure/src/nx_secure_tls_process_changecipherspec.c \
../nx_secure/src/nx_secure_tls_process_client_key_exchange.c \
../nx_secure/src/nx_secure_tls_process_clienthello.c \
../nx_secure/src/nx_secure_tls_process_clienthello_extensions.c \
../nx_secure/src/nx_secure_tls_process_encrypted_extensions.c \
../nx_secure/src/nx_secure_tls_process_finished.c \
../nx_secure/src/nx_secure_tls_process_handshake_header.c \
../nx_secure/src/nx_secure_tls_process_header.c \
../nx_secure/src/nx_secure_tls_process_newsessionticket.c \
../nx_secure/src/nx_secure_tls_process_record.c \
../nx_secure/src/nx_secure_tls_process_remote_certificate.c \
../nx_secure/src/nx_secure_tls_process_server_key_exchange.c \
../nx_secure/src/nx_secure_tls_process_serverhello.c \
../nx_secure/src/nx_secure_tls_process_serverhello_extensions.c \
../nx_secure/src/nx_secure_tls_protocol_version_get.c \
../nx_secure/src/nx_secure_tls_psk_add.c \
../nx_secure/src/nx_secure_tls_psk_binder_generate.c \
../nx_secure/src/nx_secure_tls_psk_find.c \
../nx_secure/src/nx_secure_tls_psk_identity_find.c \
../nx_secure/src/nx_secure_tls_record_hash_calculate.c \
../nx_secure/src/nx_secure_tls_record_hash_initialize.c \
../nx_secure/src/nx_secure_tls_record_hash_update.c \
../nx_secure/src/nx_secure_tls_record_payload_decrypt.c \
../nx_secure/src/nx_secure_tls_record_payload_encrypt.c \
../nx_secure/src/nx_secure_tls_remote_certificate_allocate.c \
../nx_secure/src/nx_secure_tls_remote_certificate_buffer_allocate.c \
../nx_secure/src/nx_secure_tls_remote_certificate_free.c \
../nx_secure/src/nx_secure_tls_remote_certificate_free_all.c \
../nx_secure/src/nx_secure_tls_remote_certificate_verify.c \
../nx_secure/src/nx_secure_tls_send_alert.c \
../nx_secure/src/nx_secure_tls_send_certificate.c \
../nx_secure/src/nx_secure_tls_send_certificate_request.c \
../nx_secure/src/nx_secure_tls_send_certificate_verify.c \
../nx_secure/src/nx_secure_tls_send_changecipherspec.c \
../nx_secure/src/nx_secure_tls_send_client_key_exchange.c \
../nx_secure/src/nx_secure_tls_send_clienthello.c \
../nx_secure/src/nx_secure_tls_send_clienthello_extensions.c \
../nx_secure/src/nx_secure_tls_send_encrypted_extensions.c \
../nx_secure/src/nx_secure_tls_send_finished.c \
../nx_secure/src/nx_secure_tls_send_handshake_record.c \
../nx_secure/src/nx_secure_tls_send_hellorequest.c \
../nx_secure/src/nx_secure_tls_send_newsessionticket.c \
../nx_secure/src/nx_secure_tls_send_record.c \
../nx_secure/src/nx_secure_tls_send_server_key_exchange.c \
../nx_secure/src/nx_secure_tls_send_serverhello.c \
../nx_secure/src/nx_secure_tls_send_serverhello_extensions.c \
../nx_secure/src/nx_secure_tls_server_certificate_add.c \
../nx_secure/src/nx_secure_tls_server_certificate_find.c \
../nx_secure/src/nx_secure_tls_server_certificate_remove.c \
../nx_secure/src/nx_secure_tls_server_handshake.c \
../nx_secure/src/nx_secure_tls_session_alert_value_get.c \
../nx_secure/src/nx_secure_tls_session_certificate_callback_set.c \
../nx_secure/src/nx_secure_tls_session_client_callback_set.c \
../nx_secure/src/nx_secure_tls_session_client_verify_disable.c \
../nx_secure/src/nx_secure_tls_session_client_verify_enable.c \
../nx_secure/src/nx_secure_tls_session_create.c \
../nx_secure/src/nx_secure_tls_session_create_ext.c \
../nx_secure/src/nx_secure_tls_session_delete.c \
../nx_secure/src/nx_secure_tls_session_end.c \
../nx_secure/src/nx_secure_tls_session_iv_size_get.c \
../nx_secure/src/nx_secure_tls_session_keys_set.c \
../nx_secure/src/nx_secure_tls_session_packet_buffer_set.c \
../nx_secure/src/nx_secure_tls_session_protocol_version_override.c \
../nx_secure/src/nx_secure_tls_session_receive.c \
../nx_secure/src/nx_secure_tls_session_receive_records.c \
../nx_secure/src/nx_secure_tls_session_renegotiate.c \
../nx_secure/src/nx_secure_tls_session_renegotiate_callback_set.c \
../nx_secure/src/nx_secure_tls_session_reset.c \
../nx_secure/src/nx_secure_tls_session_send.c \
../nx_secure/src/nx_secure_tls_session_server_callback_set.c \
../nx_secure/src/nx_secure_tls_session_sni_extension_parse.c \
../nx_secure/src/nx_secure_tls_session_sni_extension_set.c \
../nx_secure/src/nx_secure_tls_session_start.c \
../nx_secure/src/nx_secure_tls_session_time_function_set.c \
../nx_secure/src/nx_secure_tls_session_x509_client_verify_configure.c \
../nx_secure/src/nx_secure_tls_shutdown.c \
../nx_secure/src/nx_secure_tls_trusted_certificate_add.c \
../nx_secure/src/nx_secure_tls_trusted_certificate_remove.c \
../nx_secure/src/nx_secure_tls_verify_mac.c \
../nx_secure/src/nx_secure_x509.c \
../nx_secure/src/nx_secure_x509_asn1_tlv_block_parse.c \
../nx_secure/src/nx_secure_x509_certificate_chain_verify.c \
../nx_secure/src/nx_secure_x509_certificate_initialize.c \
../nx_secure/src/nx_secure_x509_certificate_list_add.c \
../nx_secure/src/nx_secure_x509_certificate_list_find.c \
../nx_secure/src/nx_secure_x509_certificate_list_remove.c \
../nx_secure/src/nx_secure_x509_certificate_revocation_list_parse.c \
../nx_secure/src/nx_secure_x509_certificate_verify.c \
../nx_secure/src/nx_secure_x509_common_name_dns_check.c \
../nx_secure/src/nx_secure_x509_crl_revocation_check.c \
../nx_secure/src/nx_secure_x509_crl_verify.c \
../nx_secure/src/nx_secure_x509_distinguished_name_compare.c \
../nx_secure/src/nx_secure_x509_distinguished_name_parse.c \
../nx_secure/src/nx_secure_x509_dns_name_initialize.c \
../nx_secure/src/nx_secure_x509_ec_private_key_parse.c \
../nx_secure/src/nx_secure_x509_expiration_check.c \
../nx_secure/src/nx_secure_x509_extended_key_usage_extension_parse.c \
../nx_secure/src/nx_secure_x509_extension_find.c \
../nx_secure/src/nx_secure_x509_find_certificate_methods.c \
../nx_secure/src/nx_secure_x509_free_certificate_get.c \
../nx_secure/src/nx_secure_x509_key_usage_extension_parse.c \
../nx_secure/src/nx_secure_x509_local_certificate_find.c \
../nx_secure/src/nx_secure_x509_local_device_certificate_get.c \
../nx_secure/src/nx_secure_x509_oid_parse.c \
../nx_secure/src/nx_secure_x509_pkcs1_rsa_private_key_parse.c \
../nx_secure/src/nx_secure_x509_pkcs7_decode.c \
../nx_secure/src/nx_secure_x509_remote_endpoint_certificate_get.c \
../nx_secure/src/nx_secure_x509_store_certificate_add.c \
../nx_secure/src/nx_secure_x509_store_certificate_find.c \
../nx_secure/src/nx_secure_x509_store_certificate_remove.c \
../nx_secure/src/nx_secure_x509_subject_alt_names_find.c \
../nx_secure/src/nx_secure_x509_wildcard_compare.c \
../nx_secure/src/nxe_secure_dtls_client_protocol_version_override.c \
../nx_secure/src/nxe_secure_dtls_client_session_start.c \
../nx_secure/src/nxe_secure_dtls_ecc_initialize.c \
../nx_secure/src/nxe_secure_dtls_packet_allocate.c \
../nx_secure/src/nxe_secure_dtls_psk_add.c \
../nx_secure/src/nxe_secure_dtls_server_create.c \
../nx_secure/src/nxe_secure_dtls_server_delete.c \
../nx_secure/src/nxe_secure_dtls_server_ecc_initialize.c \
../nx_secure/src/nxe_secure_dtls_server_local_certificate_add.c \
../nx_secure/src/nxe_secure_dtls_server_local_certificate_remove.c \
../nx_secure/src/nxe_secure_dtls_server_notify_set.c \
../nx_secure/src/nxe_secure_dtls_server_protocol_version_override.c \
../nx_secure/src/nxe_secure_dtls_server_psk_add.c \
../nx_secure/src/nxe_secure_dtls_server_session_send.c \
../nx_secure/src/nxe_secure_dtls_server_session_start.c \
../nx_secure/src/nxe_secure_dtls_server_start.c \
../nx_secure/src/nxe_secure_dtls_server_stop.c \
../nx_secure/src/nxe_secure_dtls_server_trusted_certificate_add.c \
../nx_secure/src/nxe_secure_dtls_server_trusted_certificate_remove.c \
../nx_secure/src/nxe_secure_dtls_server_x509_client_verify_configure.c \
../nx_secure/src/nxe_secure_dtls_server_x509_client_verify_disable.c \
../nx_secure/src/nxe_secure_dtls_session_client_info_get.c \
../nx_secure/src/nxe_secure_dtls_session_create.c \
../nx_secure/src/nxe_secure_dtls_session_delete.c \
../nx_secure/src/nxe_secure_dtls_session_end.c \
../nx_secure/src/nxe_secure_dtls_session_local_certificate_add.c \
../nx_secure/src/nxe_secure_dtls_session_local_certificate_remove.c \
../nx_secure/src/nxe_secure_dtls_session_receive.c \
../nx_secure/src/nxe_secure_dtls_session_reset.c \
../nx_secure/src/nxe_secure_dtls_session_send.c \
../nx_secure/src/nxe_secure_dtls_session_start.c \
../nx_secure/src/nxe_secure_dtls_session_trusted_certificate_add.c \
../nx_secure/src/nxe_secure_dtls_session_trusted_certificate_remove.c \
../nx_secure/src/nxe_secure_tls_active_certificate_set.c \
../nx_secure/src/nxe_secure_tls_client_psk_set.c \
../nx_secure/src/nxe_secure_tls_local_certificate_add.c \
../nx_secure/src/nxe_secure_tls_local_certificate_find.c \
../nx_secure/src/nxe_secure_tls_local_certificate_remove.c \
../nx_secure/src/nxe_secure_tls_metadata_size_calculate.c \
../nx_secure/src/nxe_secure_tls_packet_allocate.c \
../nx_secure/src/nxe_secure_tls_psk_add.c \
../nx_secure/src/nxe_secure_tls_remote_certificate_allocate.c \
../nx_secure/src/nxe_secure_tls_remote_certificate_buffer_allocate.c \
../nx_secure/src/nxe_secure_tls_remote_certificate_free_all.c \
../nx_secure/src/nxe_secure_tls_server_certificate_add.c \
../nx_secure/src/nxe_secure_tls_server_certificate_find.c \
../nx_secure/src/nxe_secure_tls_server_certificate_remove.c \
../nx_secure/src/nxe_secure_tls_session_alert_value_get.c \
../nx_secure/src/nxe_secure_tls_session_certificate_callback_set.c \
../nx_secure/src/nxe_secure_tls_session_client_callback_set.c \
../nx_secure/src/nxe_secure_tls_session_client_verify_disable.c \
../nx_secure/src/nxe_secure_tls_session_client_verify_enable.c \
../nx_secure/src/nxe_secure_tls_session_create.c \
../nx_secure/src/nxe_secure_tls_session_delete.c \
../nx_secure/src/nxe_secure_tls_session_end.c \
../nx_secure/src/nxe_secure_tls_session_packet_buffer_set.c \
../nx_secure/src/nxe_secure_tls_session_protocol_version_override.c \
../nx_secure/src/nxe_secure_tls_session_receive.c \
../nx_secure/src/nxe_secure_tls_session_renegotiate.c \
../nx_secure/src/nxe_secure_tls_session_renegotiate_callback_set.c \
../nx_secure/src/nxe_secure_tls_session_reset.c \
../nx_secure/src/nxe_secure_tls_session_send.c \
../nx_secure/src/nxe_secure_tls_session_server_callback_set.c \
../nx_secure/src/nxe_secure_tls_session_sni_extension_parse.c \
../nx_secure/src/nxe_secure_tls_session_sni_extension_set.c \
../nx_secure/src/nxe_secure_tls_session_start.c \
../nx_secure/src/nxe_secure_tls_session_time_function_set.c \
../nx_secure/src/nxe_secure_tls_session_x509_client_verify_configure.c \
../nx_secure/src/nxe_secure_tls_trusted_certificate_add.c \
../nx_secure/src/nxe_secure_tls_trusted_certificate_remove.c \
../nx_secure/src/nxe_secure_x509_certificate_initialize.c \
../nx_secure/src/nxe_secure_x509_common_name_dns_check.c \
../nx_secure/src/nxe_secure_x509_crl_revocation_check.c \
../nx_secure/src/nxe_secure_x509_dns_name_initialize.c \
../nx_secure/src/nxe_secure_x509_extended_key_usage_extension_parse.c \
../nx_secure/src/nxe_secure_x509_extension_find.c \
../nx_secure/src/nxe_secure_x509_key_usage_extension_parse.c 

C_DEPS += \
./nx_secure/src/nx_secure_crypto_method_self_test_3des.d \
./nx_secure/src/nx_secure_crypto_method_self_test_aes.d \
./nx_secure/src/nx_secure_crypto_method_self_test_des.d \
./nx_secure/src/nx_secure_crypto_method_self_test_hmac_md5.d \
./nx_secure/src/nx_secure_crypto_method_self_test_hmac_sha.d \
./nx_secure/src/nx_secure_crypto_method_self_test_md5.d \
./nx_secure/src/nx_secure_crypto_method_self_test_prf.d \
./nx_secure/src/nx_secure_crypto_method_self_test_rsa.d \
./nx_secure/src/nx_secure_crypto_method_self_test_sha.d \
./nx_secure/src/nx_secure_crypto_rng_self_test.d \
./nx_secure/src/nx_secure_crypto_table_self_test.d \
./nx_secure/src/nx_secure_dtls_allocate_handshake_packet.d \
./nx_secure/src/nx_secure_dtls_client_handshake.d \
./nx_secure/src/nx_secure_dtls_client_protocol_version_override.d \
./nx_secure/src/nx_secure_dtls_client_session_start.d \
./nx_secure/src/nx_secure_dtls_ecc_initialize.d \
./nx_secure/src/nx_secure_dtls_hash_record.d \
./nx_secure/src/nx_secure_dtls_initialize.d \
./nx_secure/src/nx_secure_dtls_packet_allocate.d \
./nx_secure/src/nx_secure_dtls_process_clienthello.d \
./nx_secure/src/nx_secure_dtls_process_handshake_header.d \
./nx_secure/src/nx_secure_dtls_process_header.d \
./nx_secure/src/nx_secure_dtls_process_helloverifyrequest.d \
./nx_secure/src/nx_secure_dtls_process_record.d \
./nx_secure/src/nx_secure_dtls_psk_add.d \
./nx_secure/src/nx_secure_dtls_receive_callback.d \
./nx_secure/src/nx_secure_dtls_retransmit.d \
./nx_secure/src/nx_secure_dtls_retransmit_queue_flush.d \
./nx_secure/src/nx_secure_dtls_send_clienthello.d \
./nx_secure/src/nx_secure_dtls_send_handshake_record.d \
./nx_secure/src/nx_secure_dtls_send_helloverifyrequest.d \
./nx_secure/src/nx_secure_dtls_send_record.d \
./nx_secure/src/nx_secure_dtls_send_serverhello.d \
./nx_secure/src/nx_secure_dtls_server_create.d \
./nx_secure/src/nx_secure_dtls_server_delete.d \
./nx_secure/src/nx_secure_dtls_server_ecc_initialize.d \
./nx_secure/src/nx_secure_dtls_server_handshake.d \
./nx_secure/src/nx_secure_dtls_server_local_certificate_add.d \
./nx_secure/src/nx_secure_dtls_server_local_certificate_remove.d \
./nx_secure/src/nx_secure_dtls_server_notify_set.d \
./nx_secure/src/nx_secure_dtls_server_protocol_version_override.d \
./nx_secure/src/nx_secure_dtls_server_psk_add.d \
./nx_secure/src/nx_secure_dtls_server_session_send.d \
./nx_secure/src/nx_secure_dtls_server_session_start.d \
./nx_secure/src/nx_secure_dtls_server_start.d \
./nx_secure/src/nx_secure_dtls_server_stop.d \
./nx_secure/src/nx_secure_dtls_server_trusted_certificate_add.d \
./nx_secure/src/nx_secure_dtls_server_trusted_certificate_remove.d \
./nx_secure/src/nx_secure_dtls_server_x509_client_verify_configure.d \
./nx_secure/src/nx_secure_dtls_server_x509_client_verify_disable.d \
./nx_secure/src/nx_secure_dtls_session_cache.d \
./nx_secure/src/nx_secure_dtls_session_client_info_get.d \
./nx_secure/src/nx_secure_dtls_session_create.d \
./nx_secure/src/nx_secure_dtls_session_delete.d \
./nx_secure/src/nx_secure_dtls_session_end.d \
./nx_secure/src/nx_secure_dtls_session_local_certificate_add.d \
./nx_secure/src/nx_secure_dtls_session_local_certificate_remove.d \
./nx_secure/src/nx_secure_dtls_session_receive.d \
./nx_secure/src/nx_secure_dtls_session_reset.d \
./nx_secure/src/nx_secure_dtls_session_send.d \
./nx_secure/src/nx_secure_dtls_session_start.d \
./nx_secure/src/nx_secure_dtls_session_trusted_certificate_add.d \
./nx_secure/src/nx_secure_dtls_session_trusted_certificate_remove.d \
./nx_secure/src/nx_secure_dtls_verify_mac.d \
./nx_secure/src/nx_secure_module_hash_compute.d \
./nx_secure/src/nx_secure_tls_1_3_client_handshake.d \
./nx_secure/src/nx_secure_tls_1_3_crypto_init.d \
./nx_secure/src/nx_secure_tls_1_3_finished_hash_generate.d \
./nx_secure/src/nx_secure_tls_1_3_generate_keys.d \
./nx_secure/src/nx_secure_tls_1_3_server_handshake.d \
./nx_secure/src/nx_secure_tls_1_3_session_keys_set.d \
./nx_secure/src/nx_secure_tls_1_3_transcript_hash_save.d \
./nx_secure/src/nx_secure_tls_active_certificate_set.d \
./nx_secure/src/nx_secure_tls_allocate_handshake_packet.d \
./nx_secure/src/nx_secure_tls_check_protocol_version.d \
./nx_secure/src/nx_secure_tls_ciphersuite_lookup.d \
./nx_secure/src/nx_secure_tls_client_handshake.d \
./nx_secure/src/nx_secure_tls_client_psk_set.d \
./nx_secure/src/nx_secure_tls_ecc_generate_keys.d \
./nx_secure/src/nx_secure_tls_ecc_initialize.d \
./nx_secure/src/nx_secure_tls_find_curve_method.d \
./nx_secure/src/nx_secure_tls_finished_hash_generate.d \
./nx_secure/src/nx_secure_tls_generate_keys.d \
./nx_secure/src/nx_secure_tls_generate_premaster_secret.d \
./nx_secure/src/nx_secure_tls_handshake_hash_init.d \
./nx_secure/src/nx_secure_tls_handshake_hash_update.d \
./nx_secure/src/nx_secure_tls_handshake_process.d \
./nx_secure/src/nx_secure_tls_hash_record.d \
./nx_secure/src/nx_secure_tls_initialize.d \
./nx_secure/src/nx_secure_tls_key_material_init.d \
./nx_secure/src/nx_secure_tls_local_certificate_add.d \
./nx_secure/src/nx_secure_tls_local_certificate_find.d \
./nx_secure/src/nx_secure_tls_local_certificate_remove.d \
./nx_secure/src/nx_secure_tls_map_error_to_alert.d \
./nx_secure/src/nx_secure_tls_metadata_size_calculate.d \
./nx_secure/src/nx_secure_tls_newest_supported_version.d \
./nx_secure/src/nx_secure_tls_packet_allocate.d \
./nx_secure/src/nx_secure_tls_packet_release.d \
./nx_secure/src/nx_secure_tls_process_certificate_request.d \
./nx_secure/src/nx_secure_tls_process_certificate_verify.d \
./nx_secure/src/nx_secure_tls_process_changecipherspec.d \
./nx_secure/src/nx_secure_tls_process_client_key_exchange.d \
./nx_secure/src/nx_secure_tls_process_clienthello.d \
./nx_secure/src/nx_secure_tls_process_clienthello_extensions.d \
./nx_secure/src/nx_secure_tls_process_encrypted_extensions.d \
./nx_secure/src/nx_secure_tls_process_finished.d \
./nx_secure/src/nx_secure_tls_process_handshake_header.d \
./nx_secure/src/nx_secure_tls_process_header.d \
./nx_secure/src/nx_secure_tls_process_newsessionticket.d \
./nx_secure/src/nx_secure_tls_process_record.d \
./nx_secure/src/nx_secure_tls_process_remote_certificate.d \
./nx_secure/src/nx_secure_tls_process_server_key_exchange.d \
./nx_secure/src/nx_secure_tls_process_serverhello.d \
./nx_secure/src/nx_secure_tls_process_serverhello_extensions.d \
./nx_secure/src/nx_secure_tls_protocol_version_get.d \
./nx_secure/src/nx_secure_tls_psk_add.d \
./nx_secure/src/nx_secure_tls_psk_binder_generate.d \
./nx_secure/src/nx_secure_tls_psk_find.d \
./nx_secure/src/nx_secure_tls_psk_identity_find.d \
./nx_secure/src/nx_secure_tls_record_hash_calculate.d \
./nx_secure/src/nx_secure_tls_record_hash_initialize.d \
./nx_secure/src/nx_secure_tls_record_hash_update.d \
./nx_secure/src/nx_secure_tls_record_payload_decrypt.d \
./nx_secure/src/nx_secure_tls_record_payload_encrypt.d \
./nx_secure/src/nx_secure_tls_remote_certificate_allocate.d \
./nx_secure/src/nx_secure_tls_remote_certificate_buffer_allocate.d \
./nx_secure/src/nx_secure_tls_remote_certificate_free.d \
./nx_secure/src/nx_secure_tls_remote_certificate_free_all.d \
./nx_secure/src/nx_secure_tls_remote_certificate_verify.d \
./nx_secure/src/nx_secure_tls_send_alert.d \
./nx_secure/src/nx_secure_tls_send_certificate.d \
./nx_secure/src/nx_secure_tls_send_certificate_request.d \
./nx_secure/src/nx_secure_tls_send_certificate_verify.d \
./nx_secure/src/nx_secure_tls_send_changecipherspec.d \
./nx_secure/src/nx_secure_tls_send_client_key_exchange.d \
./nx_secure/src/nx_secure_tls_send_clienthello.d \
./nx_secure/src/nx_secure_tls_send_clienthello_extensions.d \
./nx_secure/src/nx_secure_tls_send_encrypted_extensions.d \
./nx_secure/src/nx_secure_tls_send_finished.d \
./nx_secure/src/nx_secure_tls_send_handshake_record.d \
./nx_secure/src/nx_secure_tls_send_hellorequest.d \
./nx_secure/src/nx_secure_tls_send_newsessionticket.d \
./nx_secure/src/nx_secure_tls_send_record.d \
./nx_secure/src/nx_secure_tls_send_server_key_exchange.d \
./nx_secure/src/nx_secure_tls_send_serverhello.d \
./nx_secure/src/nx_secure_tls_send_serverhello_extensions.d \
./nx_secure/src/nx_secure_tls_server_certificate_add.d \
./nx_secure/src/nx_secure_tls_server_certificate_find.d \
./nx_secure/src/nx_secure_tls_server_certificate_remove.d \
./nx_secure/src/nx_secure_tls_server_handshake.d \
./nx_secure/src/nx_secure_tls_session_alert_value_get.d \
./nx_secure/src/nx_secure_tls_session_certificate_callback_set.d \
./nx_secure/src/nx_secure_tls_session_client_callback_set.d \
./nx_secure/src/nx_secure_tls_session_client_verify_disable.d \
./nx_secure/src/nx_secure_tls_session_client_verify_enable.d \
./nx_secure/src/nx_secure_tls_session_create.d \
./nx_secure/src/nx_secure_tls_session_create_ext.d \
./nx_secure/src/nx_secure_tls_session_delete.d \
./nx_secure/src/nx_secure_tls_session_end.d \
./nx_secure/src/nx_secure_tls_session_iv_size_get.d \
./nx_secure/src/nx_secure_tls_session_keys_set.d \
./nx_secure/src/nx_secure_tls_session_packet_buffer_set.d \
./nx_secure/src/nx_secure_tls_session_protocol_version_override.d \
./nx_secure/src/nx_secure_tls_session_receive.d \
./nx_secure/src/nx_secure_tls_session_receive_records.d \
./nx_secure/src/nx_secure_tls_session_renegotiate.d \
./nx_secure/src/nx_secure_tls_session_renegotiate_callback_set.d \
./nx_secure/src/nx_secure_tls_session_reset.d \
./nx_secure/src/nx_secure_tls_session_send.d \
./nx_secure/src/nx_secure_tls_session_server_callback_set.d \
./nx_secure/src/nx_secure_tls_session_sni_extension_parse.d \
./nx_secure/src/nx_secure_tls_session_sni_extension_set.d \
./nx_secure/src/nx_secure_tls_session_start.d \
./nx_secure/src/nx_secure_tls_session_time_function_set.d \
./nx_secure/src/nx_secure_tls_session_x509_client_verify_configure.d \
./nx_secure/src/nx_secure_tls_shutdown.d \
./nx_secure/src/nx_secure_tls_trusted_certificate_add.d \
./nx_secure/src/nx_secure_tls_trusted_certificate_remove.d \
./nx_secure/src/nx_secure_tls_verify_mac.d \
./nx_secure/src/nx_secure_x509.d \
./nx_secure/src/nx_secure_x509_asn1_tlv_block_parse.d \
./nx_secure/src/nx_secure_x509_certificate_chain_verify.d \
./nx_secure/src/nx_secure_x509_certificate_initialize.d \
./nx_secure/src/nx_secure_x509_certificate_list_add.d \
./nx_secure/src/nx_secure_x509_certificate_list_find.d \
./nx_secure/src/nx_secure_x509_certificate_list_remove.d \
./nx_secure/src/nx_secure_x509_certificate_revocation_list_parse.d \
./nx_secure/src/nx_secure_x509_certificate_verify.d \
./nx_secure/src/nx_secure_x509_common_name_dns_check.d \
./nx_secure/src/nx_secure_x509_crl_revocation_check.d \
./nx_secure/src/nx_secure_x509_crl_verify.d \
./nx_secure/src/nx_secure_x509_distinguished_name_compare.d \
./nx_secure/src/nx_secure_x509_distinguished_name_parse.d \
./nx_secure/src/nx_secure_x509_dns_name_initialize.d \
./nx_secure/src/nx_secure_x509_ec_private_key_parse.d \
./nx_secure/src/nx_secure_x509_expiration_check.d \
./nx_secure/src/nx_secure_x509_extended_key_usage_extension_parse.d \
./nx_secure/src/nx_secure_x509_extension_find.d \
./nx_secure/src/nx_secure_x509_find_certificate_methods.d \
./nx_secure/src/nx_secure_x509_free_certificate_get.d \
./nx_secure/src/nx_secure_x509_key_usage_extension_parse.d \
./nx_secure/src/nx_secure_x509_local_certificate_find.d \
./nx_secure/src/nx_secure_x509_local_device_certificate_get.d \
./nx_secure/src/nx_secure_x509_oid_parse.d \
./nx_secure/src/nx_secure_x509_pkcs1_rsa_private_key_parse.d \
./nx_secure/src/nx_secure_x509_pkcs7_decode.d \
./nx_secure/src/nx_secure_x509_remote_endpoint_certificate_get.d \
./nx_secure/src/nx_secure_x509_store_certificate_add.d \
./nx_secure/src/nx_secure_x509_store_certificate_find.d \
./nx_secure/src/nx_secure_x509_store_certificate_remove.d \
./nx_secure/src/nx_secure_x509_subject_alt_names_find.d \
./nx_secure/src/nx_secure_x509_wildcard_compare.d \
./nx_secure/src/nxe_secure_dtls_client_protocol_version_override.d \
./nx_secure/src/nxe_secure_dtls_client_session_start.d \
./nx_secure/src/nxe_secure_dtls_ecc_initialize.d \
./nx_secure/src/nxe_secure_dtls_packet_allocate.d \
./nx_secure/src/nxe_secure_dtls_psk_add.d \
./nx_secure/src/nxe_secure_dtls_server_create.d \
./nx_secure/src/nxe_secure_dtls_server_delete.d \
./nx_secure/src/nxe_secure_dtls_server_ecc_initialize.d \
./nx_secure/src/nxe_secure_dtls_server_local_certificate_add.d \
./nx_secure/src/nxe_secure_dtls_server_local_certificate_remove.d \
./nx_secure/src/nxe_secure_dtls_server_notify_set.d \
./nx_secure/src/nxe_secure_dtls_server_protocol_version_override.d \
./nx_secure/src/nxe_secure_dtls_server_psk_add.d \
./nx_secure/src/nxe_secure_dtls_server_session_send.d \
./nx_secure/src/nxe_secure_dtls_server_session_start.d \
./nx_secure/src/nxe_secure_dtls_server_start.d \
./nx_secure/src/nxe_secure_dtls_server_stop.d \
./nx_secure/src/nxe_secure_dtls_server_trusted_certificate_add.d \
./nx_secure/src/nxe_secure_dtls_server_trusted_certificate_remove.d \
./nx_secure/src/nxe_secure_dtls_server_x509_client_verify_configure.d \
./nx_secure/src/nxe_secure_dtls_server_x509_client_verify_disable.d \
./nx_secure/src/nxe_secure_dtls_session_client_info_get.d \
./nx_secure/src/nxe_secure_dtls_session_create.d \
./nx_secure/src/nxe_secure_dtls_session_delete.d \
./nx_secure/src/nxe_secure_dtls_session_end.d \
./nx_secure/src/nxe_secure_dtls_session_local_certificate_add.d \
./nx_secure/src/nxe_secure_dtls_session_local_certificate_remove.d \
./nx_secure/src/nxe_secure_dtls_session_receive.d \
./nx_secure/src/nxe_secure_dtls_session_reset.d \
./nx_secure/src/nxe_secure_dtls_session_send.d \
./nx_secure/src/nxe_secure_dtls_session_start.d \
./nx_secure/src/nxe_secure_dtls_session_trusted_certificate_add.d \
./nx_secure/src/nxe_secure_dtls_session_trusted_certificate_remove.d \
./nx_secure/src/nxe_secure_tls_active_certificate_set.d \
./nx_secure/src/nxe_secure_tls_client_psk_set.d \
./nx_secure/src/nxe_secure_tls_local_certificate_add.d \
./nx_secure/src/nxe_secure_tls_local_certificate_find.d \
./nx_secure/src/nxe_secure_tls_local_certificate_remove.d \
./nx_secure/src/nxe_secure_tls_metadata_size_calculate.d \
./nx_secure/src/nxe_secure_tls_packet_allocate.d \
./nx_secure/src/nxe_secure_tls_psk_add.d \
./nx_secure/src/nxe_secure_tls_remote_certificate_allocate.d \
./nx_secure/src/nxe_secure_tls_remote_certificate_buffer_allocate.d \
./nx_secure/src/nxe_secure_tls_remote_certificate_free_all.d \
./nx_secure/src/nxe_secure_tls_server_certificate_add.d \
./nx_secure/src/nxe_secure_tls_server_certificate_find.d \
./nx_secure/src/nxe_secure_tls_server_certificate_remove.d \
./nx_secure/src/nxe_secure_tls_session_alert_value_get.d \
./nx_secure/src/nxe_secure_tls_session_certificate_callback_set.d \
./nx_secure/src/nxe_secure_tls_session_client_callback_set.d \
./nx_secure/src/nxe_secure_tls_session_client_verify_disable.d \
./nx_secure/src/nxe_secure_tls_session_client_verify_enable.d \
./nx_secure/src/nxe_secure_tls_session_create.d \
./nx_secure/src/nxe_secure_tls_session_delete.d \
./nx_secure/src/nxe_secure_tls_session_end.d \
./nx_secure/src/nxe_secure_tls_session_packet_buffer_set.d \
./nx_secure/src/nxe_secure_tls_session_protocol_version_override.d \
./nx_secure/src/nxe_secure_tls_session_receive.d \
./nx_secure/src/nxe_secure_tls_session_renegotiate.d \
./nx_secure/src/nxe_secure_tls_session_renegotiate_callback_set.d \
./nx_secure/src/nxe_secure_tls_session_reset.d \
./nx_secure/src/nxe_secure_tls_session_send.d \
./nx_secure/src/nxe_secure_tls_session_server_callback_set.d \
./nx_secure/src/nxe_secure_tls_session_sni_extension_parse.d \
./nx_secure/src/nxe_secure_tls_session_sni_extension_set.d \
./nx_secure/src/nxe_secure_tls_session_start.d \
./nx_secure/src/nxe_secure_tls_session_time_function_set.d \
./nx_secure/src/nxe_secure_tls_session_x509_client_verify_configure.d \
./nx_secure/src/nxe_secure_tls_trusted_certificate_add.d \
./nx_secure/src/nxe_secure_tls_trusted_certificate_remove.d \
./nx_secure/src/nxe_secure_x509_certificate_initialize.d \
./nx_secure/src/nxe_secure_x509_common_name_dns_check.d \
./nx_secure/src/nxe_secure_x509_crl_revocation_check.d \
./nx_secure/src/nxe_secure_x509_dns_name_initialize.d \
./nx_secure/src/nxe_secure_x509_extended_key_usage_extension_parse.d \
./nx_secure/src/nxe_secure_x509_extension_find.d \
./nx_secure/src/nxe_secure_x509_key_usage_extension_parse.d 

OBJS += \
./nx_secure/src/nx_secure_crypto_method_self_test_3des.o \
./nx_secure/src/nx_secure_crypto_method_self_test_aes.o \
./nx_secure/src/nx_secure_crypto_method_self_test_des.o \
./nx_secure/src/nx_secure_crypto_method_self_test_hmac_md5.o \
./nx_secure/src/nx_secure_crypto_method_self_test_hmac_sha.o \
./nx_secure/src/nx_secure_crypto_method_self_test_md5.o \
./nx_secure/src/nx_secure_crypto_method_self_test_prf.o \
./nx_secure/src/nx_secure_crypto_method_self_test_rsa.o \
./nx_secure/src/nx_secure_crypto_method_self_test_sha.o \
./nx_secure/src/nx_secure_crypto_rng_self_test.o \
./nx_secure/src/nx_secure_crypto_table_self_test.o \
./nx_secure/src/nx_secure_dtls_allocate_handshake_packet.o \
./nx_secure/src/nx_secure_dtls_client_handshake.o \
./nx_secure/src/nx_secure_dtls_client_protocol_version_override.o \
./nx_secure/src/nx_secure_dtls_client_session_start.o \
./nx_secure/src/nx_secure_dtls_ecc_initialize.o \
./nx_secure/src/nx_secure_dtls_hash_record.o \
./nx_secure/src/nx_secure_dtls_initialize.o \
./nx_secure/src/nx_secure_dtls_packet_allocate.o \
./nx_secure/src/nx_secure_dtls_process_clienthello.o \
./nx_secure/src/nx_secure_dtls_process_handshake_header.o \
./nx_secure/src/nx_secure_dtls_process_header.o \
./nx_secure/src/nx_secure_dtls_process_helloverifyrequest.o \
./nx_secure/src/nx_secure_dtls_process_record.o \
./nx_secure/src/nx_secure_dtls_psk_add.o \
./nx_secure/src/nx_secure_dtls_receive_callback.o \
./nx_secure/src/nx_secure_dtls_retransmit.o \
./nx_secure/src/nx_secure_dtls_retransmit_queue_flush.o \
./nx_secure/src/nx_secure_dtls_send_clienthello.o \
./nx_secure/src/nx_secure_dtls_send_handshake_record.o \
./nx_secure/src/nx_secure_dtls_send_helloverifyrequest.o \
./nx_secure/src/nx_secure_dtls_send_record.o \
./nx_secure/src/nx_secure_dtls_send_serverhello.o \
./nx_secure/src/nx_secure_dtls_server_create.o \
./nx_secure/src/nx_secure_dtls_server_delete.o \
./nx_secure/src/nx_secure_dtls_server_ecc_initialize.o \
./nx_secure/src/nx_secure_dtls_server_handshake.o \
./nx_secure/src/nx_secure_dtls_server_local_certificate_add.o \
./nx_secure/src/nx_secure_dtls_server_local_certificate_remove.o \
./nx_secure/src/nx_secure_dtls_server_notify_set.o \
./nx_secure/src/nx_secure_dtls_server_protocol_version_override.o \
./nx_secure/src/nx_secure_dtls_server_psk_add.o \
./nx_secure/src/nx_secure_dtls_server_session_send.o \
./nx_secure/src/nx_secure_dtls_server_session_start.o \
./nx_secure/src/nx_secure_dtls_server_start.o \
./nx_secure/src/nx_secure_dtls_server_stop.o \
./nx_secure/src/nx_secure_dtls_server_trusted_certificate_add.o \
./nx_secure/src/nx_secure_dtls_server_trusted_certificate_remove.o \
./nx_secure/src/nx_secure_dtls_server_x509_client_verify_configure.o \
./nx_secure/src/nx_secure_dtls_server_x509_client_verify_disable.o \
./nx_secure/src/nx_secure_dtls_session_cache.o \
./nx_secure/src/nx_secure_dtls_session_client_info_get.o \
./nx_secure/src/nx_secure_dtls_session_create.o \
./nx_secure/src/nx_secure_dtls_session_delete.o \
./nx_secure/src/nx_secure_dtls_session_end.o \
./nx_secure/src/nx_secure_dtls_session_local_certificate_add.o \
./nx_secure/src/nx_secure_dtls_session_local_certificate_remove.o \
./nx_secure/src/nx_secure_dtls_session_receive.o \
./nx_secure/src/nx_secure_dtls_session_reset.o \
./nx_secure/src/nx_secure_dtls_session_send.o \
./nx_secure/src/nx_secure_dtls_session_start.o \
./nx_secure/src/nx_secure_dtls_session_trusted_certificate_add.o \
./nx_secure/src/nx_secure_dtls_session_trusted_certificate_remove.o \
./nx_secure/src/nx_secure_dtls_verify_mac.o \
./nx_secure/src/nx_secure_module_hash_compute.o \
./nx_secure/src/nx_secure_tls_1_3_client_handshake.o \
./nx_secure/src/nx_secure_tls_1_3_crypto_init.o \
./nx_secure/src/nx_secure_tls_1_3_finished_hash_generate.o \
./nx_secure/src/nx_secure_tls_1_3_generate_keys.o \
./nx_secure/src/nx_secure_tls_1_3_server_handshake.o \
./nx_secure/src/nx_secure_tls_1_3_session_keys_set.o \
./nx_secure/src/nx_secure_tls_1_3_transcript_hash_save.o \
./nx_secure/src/nx_secure_tls_active_certificate_set.o \
./nx_secure/src/nx_secure_tls_allocate_handshake_packet.o \
./nx_secure/src/nx_secure_tls_check_protocol_version.o \
./nx_secure/src/nx_secure_tls_ciphersuite_lookup.o \
./nx_secure/src/nx_secure_tls_client_handshake.o \
./nx_secure/src/nx_secure_tls_client_psk_set.o \
./nx_secure/src/nx_secure_tls_ecc_generate_keys.o \
./nx_secure/src/nx_secure_tls_ecc_initialize.o \
./nx_secure/src/nx_secure_tls_find_curve_method.o \
./nx_secure/src/nx_secure_tls_finished_hash_generate.o \
./nx_secure/src/nx_secure_tls_generate_keys.o \
./nx_secure/src/nx_secure_tls_generate_premaster_secret.o \
./nx_secure/src/nx_secure_tls_handshake_hash_init.o \
./nx_secure/src/nx_secure_tls_handshake_hash_update.o \
./nx_secure/src/nx_secure_tls_handshake_process.o \
./nx_secure/src/nx_secure_tls_hash_record.o \
./nx_secure/src/nx_secure_tls_initialize.o \
./nx_secure/src/nx_secure_tls_key_material_init.o \
./nx_secure/src/nx_secure_tls_local_certificate_add.o \
./nx_secure/src/nx_secure_tls_local_certificate_find.o \
./nx_secure/src/nx_secure_tls_local_certificate_remove.o \
./nx_secure/src/nx_secure_tls_map_error_to_alert.o \
./nx_secure/src/nx_secure_tls_metadata_size_calculate.o \
./nx_secure/src/nx_secure_tls_newest_supported_version.o \
./nx_secure/src/nx_secure_tls_packet_allocate.o \
./nx_secure/src/nx_secure_tls_packet_release.o \
./nx_secure/src/nx_secure_tls_process_certificate_request.o \
./nx_secure/src/nx_secure_tls_process_certificate_verify.o \
./nx_secure/src/nx_secure_tls_process_changecipherspec.o \
./nx_secure/src/nx_secure_tls_process_client_key_exchange.o \
./nx_secure/src/nx_secure_tls_process_clienthello.o \
./nx_secure/src/nx_secure_tls_process_clienthello_extensions.o \
./nx_secure/src/nx_secure_tls_process_encrypted_extensions.o \
./nx_secure/src/nx_secure_tls_process_finished.o \
./nx_secure/src/nx_secure_tls_process_handshake_header.o \
./nx_secure/src/nx_secure_tls_process_header.o \
./nx_secure/src/nx_secure_tls_process_newsessionticket.o \
./nx_secure/src/nx_secure_tls_process_record.o \
./nx_secure/src/nx_secure_tls_process_remote_certificate.o \
./nx_secure/src/nx_secure_tls_process_server_key_exchange.o \
./nx_secure/src/nx_secure_tls_process_serverhello.o \
./nx_secure/src/nx_secure_tls_process_serverhello_extensions.o \
./nx_secure/src/nx_secure_tls_protocol_version_get.o \
./nx_secure/src/nx_secure_tls_psk_add.o \
./nx_secure/src/nx_secure_tls_psk_binder_generate.o \
./nx_secure/src/nx_secure_tls_psk_find.o \
./nx_secure/src/nx_secure_tls_psk_identity_find.o \
./nx_secure/src/nx_secure_tls_record_hash_calculate.o \
./nx_secure/src/nx_secure_tls_record_hash_initialize.o \
./nx_secure/src/nx_secure_tls_record_hash_update.o \
./nx_secure/src/nx_secure_tls_record_payload_decrypt.o \
./nx_secure/src/nx_secure_tls_record_payload_encrypt.o \
./nx_secure/src/nx_secure_tls_remote_certificate_allocate.o \
./nx_secure/src/nx_secure_tls_remote_certificate_buffer_allocate.o \
./nx_secure/src/nx_secure_tls_remote_certificate_free.o \
./nx_secure/src/nx_secure_tls_remote_certificate_free_all.o \
./nx_secure/src/nx_secure_tls_remote_certificate_verify.o \
./nx_secure/src/nx_secure_tls_send_alert.o \
./nx_secure/src/nx_secure_tls_send_certificate.o \
./nx_secure/src/nx_secure_tls_send_certificate_request.o \
./nx_secure/src/nx_secure_tls_send_certificate_verify.o \
./nx_secure/src/nx_secure_tls_send_changecipherspec.o \
./nx_secure/src/nx_secure_tls_send_client_key_exchange.o \
./nx_secure/src/nx_secure_tls_send_clienthello.o \
./nx_secure/src/nx_secure_tls_send_clienthello_extensions.o \
./nx_secure/src/nx_secure_tls_send_encrypted_extensions.o \
./nx_secure/src/nx_secure_tls_send_finished.o \
./nx_secure/src/nx_secure_tls_send_handshake_record.o \
./nx_secure/src/nx_secure_tls_send_hellorequest.o \
./nx_secure/src/nx_secure_tls_send_newsessionticket.o \
./nx_secure/src/nx_secure_tls_send_record.o \
./nx_secure/src/nx_secure_tls_send_server_key_exchange.o \
./nx_secure/src/nx_secure_tls_send_serverhello.o \
./nx_secure/src/nx_secure_tls_send_serverhello_extensions.o \
./nx_secure/src/nx_secure_tls_server_certificate_add.o \
./nx_secure/src/nx_secure_tls_server_certificate_find.o \
./nx_secure/src/nx_secure_tls_server_certificate_remove.o \
./nx_secure/src/nx_secure_tls_server_handshake.o \
./nx_secure/src/nx_secure_tls_session_alert_value_get.o \
./nx_secure/src/nx_secure_tls_session_certificate_callback_set.o \
./nx_secure/src/nx_secure_tls_session_client_callback_set.o \
./nx_secure/src/nx_secure_tls_session_client_verify_disable.o \
./nx_secure/src/nx_secure_tls_session_client_verify_enable.o \
./nx_secure/src/nx_secure_tls_session_create.o \
./nx_secure/src/nx_secure_tls_session_create_ext.o \
./nx_secure/src/nx_secure_tls_session_delete.o \
./nx_secure/src/nx_secure_tls_session_end.o \
./nx_secure/src/nx_secure_tls_session_iv_size_get.o \
./nx_secure/src/nx_secure_tls_session_keys_set.o \
./nx_secure/src/nx_secure_tls_session_packet_buffer_set.o \
./nx_secure/src/nx_secure_tls_session_protocol_version_override.o \
./nx_secure/src/nx_secure_tls_session_receive.o \
./nx_secure/src/nx_secure_tls_session_receive_records.o \
./nx_secure/src/nx_secure_tls_session_renegotiate.o \
./nx_secure/src/nx_secure_tls_session_renegotiate_callback_set.o \
./nx_secure/src/nx_secure_tls_session_reset.o \
./nx_secure/src/nx_secure_tls_session_send.o \
./nx_secure/src/nx_secure_tls_session_server_callback_set.o \
./nx_secure/src/nx_secure_tls_session_sni_extension_parse.o \
./nx_secure/src/nx_secure_tls_session_sni_extension_set.o \
./nx_secure/src/nx_secure_tls_session_start.o \
./nx_secure/src/nx_secure_tls_session_time_function_set.o \
./nx_secure/src/nx_secure_tls_session_x509_client_verify_configure.o \
./nx_secure/src/nx_secure_tls_shutdown.o \
./nx_secure/src/nx_secure_tls_trusted_certificate_add.o \
./nx_secure/src/nx_secure_tls_trusted_certificate_remove.o \
./nx_secure/src/nx_secure_tls_verify_mac.o \
./nx_secure/src/nx_secure_x509.o \
./nx_secure/src/nx_secure_x509_asn1_tlv_block_parse.o \
./nx_secure/src/nx_secure_x509_certificate_chain_verify.o \
./nx_secure/src/nx_secure_x509_certificate_initialize.o \
./nx_secure/src/nx_secure_x509_certificate_list_add.o \
./nx_secure/src/nx_secure_x509_certificate_list_find.o \
./nx_secure/src/nx_secure_x509_certificate_list_remove.o \
./nx_secure/src/nx_secure_x509_certificate_revocation_list_parse.o \
./nx_secure/src/nx_secure_x509_certificate_verify.o \
./nx_secure/src/nx_secure_x509_common_name_dns_check.o \
./nx_secure/src/nx_secure_x509_crl_revocation_check.o \
./nx_secure/src/nx_secure_x509_crl_verify.o \
./nx_secure/src/nx_secure_x509_distinguished_name_compare.o \
./nx_secure/src/nx_secure_x509_distinguished_name_parse.o \
./nx_secure/src/nx_secure_x509_dns_name_initialize.o \
./nx_secure/src/nx_secure_x509_ec_private_key_parse.o \
./nx_secure/src/nx_secure_x509_expiration_check.o \
./nx_secure/src/nx_secure_x509_extended_key_usage_extension_parse.o \
./nx_secure/src/nx_secure_x509_extension_find.o \
./nx_secure/src/nx_secure_x509_find_certificate_methods.o \
./nx_secure/src/nx_secure_x509_free_certificate_get.o \
./nx_secure/src/nx_secure_x509_key_usage_extension_parse.o \
./nx_secure/src/nx_secure_x509_local_certificate_find.o \
./nx_secure/src/nx_secure_x509_local_device_certificate_get.o \
./nx_secure/src/nx_secure_x509_oid_parse.o \
./nx_secure/src/nx_secure_x509_pkcs1_rsa_private_key_parse.o \
./nx_secure/src/nx_secure_x509_pkcs7_decode.o \
./nx_secure/src/nx_secure_x509_remote_endpoint_certificate_get.o \
./nx_secure/src/nx_secure_x509_store_certificate_add.o \
./nx_secure/src/nx_secure_x509_store_certificate_find.o \
./nx_secure/src/nx_secure_x509_store_certificate_remove.o \
./nx_secure/src/nx_secure_x509_subject_alt_names_find.o \
./nx_secure/src/nx_secure_x509_wildcard_compare.o \
./nx_secure/src/nxe_secure_dtls_client_protocol_version_override.o \
./nx_secure/src/nxe_secure_dtls_client_session_start.o \
./nx_secure/src/nxe_secure_dtls_ecc_initialize.o \
./nx_secure/src/nxe_secure_dtls_packet_allocate.o \
./nx_secure/src/nxe_secure_dtls_psk_add.o \
./nx_secure/src/nxe_secure_dtls_server_create.o \
./nx_secure/src/nxe_secure_dtls_server_delete.o \
./nx_secure/src/nxe_secure_dtls_server_ecc_initialize.o \
./nx_secure/src/nxe_secure_dtls_server_local_certificate_add.o \
./nx_secure/src/nxe_secure_dtls_server_local_certificate_remove.o \
./nx_secure/src/nxe_secure_dtls_server_notify_set.o \
./nx_secure/src/nxe_secure_dtls_server_protocol_version_override.o \
./nx_secure/src/nxe_secure_dtls_server_psk_add.o \
./nx_secure/src/nxe_secure_dtls_server_session_send.o \
./nx_secure/src/nxe_secure_dtls_server_session_start.o \
./nx_secure/src/nxe_secure_dtls_server_start.o \
./nx_secure/src/nxe_secure_dtls_server_stop.o \
./nx_secure/src/nxe_secure_dtls_server_trusted_certificate_add.o \
./nx_secure/src/nxe_secure_dtls_server_trusted_certificate_remove.o \
./nx_secure/src/nxe_secure_dtls_server_x509_client_verify_configure.o \
./nx_secure/src/nxe_secure_dtls_server_x509_client_verify_disable.o \
./nx_secure/src/nxe_secure_dtls_session_client_info_get.o \
./nx_secure/src/nxe_secure_dtls_session_create.o \
./nx_secure/src/nxe_secure_dtls_session_delete.o \
./nx_secure/src/nxe_secure_dtls_session_end.o \
./nx_secure/src/nxe_secure_dtls_session_local_certificate_add.o \
./nx_secure/src/nxe_secure_dtls_session_local_certificate_remove.o \
./nx_secure/src/nxe_secure_dtls_session_receive.o \
./nx_secure/src/nxe_secure_dtls_session_reset.o \
./nx_secure/src/nxe_secure_dtls_session_send.o \
./nx_secure/src/nxe_secure_dtls_session_start.o \
./nx_secure/src/nxe_secure_dtls_session_trusted_certificate_add.o \
./nx_secure/src/nxe_secure_dtls_session_trusted_certificate_remove.o \
./nx_secure/src/nxe_secure_tls_active_certificate_set.o \
./nx_secure/src/nxe_secure_tls_client_psk_set.o \
./nx_secure/src/nxe_secure_tls_local_certificate_add.o \
./nx_secure/src/nxe_secure_tls_local_certificate_find.o \
./nx_secure/src/nxe_secure_tls_local_certificate_remove.o \
./nx_secure/src/nxe_secure_tls_metadata_size_calculate.o \
./nx_secure/src/nxe_secure_tls_packet_allocate.o \
./nx_secure/src/nxe_secure_tls_psk_add.o \
./nx_secure/src/nxe_secure_tls_remote_certificate_allocate.o \
./nx_secure/src/nxe_secure_tls_remote_certificate_buffer_allocate.o \
./nx_secure/src/nxe_secure_tls_remote_certificate_free_all.o \
./nx_secure/src/nxe_secure_tls_server_certificate_add.o \
./nx_secure/src/nxe_secure_tls_server_certificate_find.o \
./nx_secure/src/nxe_secure_tls_server_certificate_remove.o \
./nx_secure/src/nxe_secure_tls_session_alert_value_get.o \
./nx_secure/src/nxe_secure_tls_session_certificate_callback_set.o \
./nx_secure/src/nxe_secure_tls_session_client_callback_set.o \
./nx_secure/src/nxe_secure_tls_session_client_verify_disable.o \
./nx_secure/src/nxe_secure_tls_session_client_verify_enable.o \
./nx_secure/src/nxe_secure_tls_session_create.o \
./nx_secure/src/nxe_secure_tls_session_delete.o \
./nx_secure/src/nxe_secure_tls_session_end.o \
./nx_secure/src/nxe_secure_tls_session_packet_buffer_set.o \
./nx_secure/src/nxe_secure_tls_session_protocol_version_override.o \
./nx_secure/src/nxe_secure_tls_session_receive.o \
./nx_secure/src/nxe_secure_tls_session_renegotiate.o \
./nx_secure/src/nxe_secure_tls_session_renegotiate_callback_set.o \
./nx_secure/src/nxe_secure_tls_session_reset.o \
./nx_secure/src/nxe_secure_tls_session_send.o \
./nx_secure/src/nxe_secure_tls_session_server_callback_set.o \
./nx_secure/src/nxe_secure_tls_session_sni_extension_parse.o \
./nx_secure/src/nxe_secure_tls_session_sni_extension_set.o \
./nx_secure/src/nxe_secure_tls_session_start.o \
./nx_secure/src/nxe_secure_tls_session_time_function_set.o \
./nx_secure/src/nxe_secure_tls_session_x509_client_verify_configure.o \
./nx_secure/src/nxe_secure_tls_trusted_certificate_add.o \
./nx_secure/src/nxe_secure_tls_trusted_certificate_remove.o \
./nx_secure/src/nxe_secure_x509_certificate_initialize.o \
./nx_secure/src/nxe_secure_x509_common_name_dns_check.o \
./nx_secure/src/nxe_secure_x509_crl_revocation_check.o \
./nx_secure/src/nxe_secure_x509_dns_name_initialize.o \
./nx_secure/src/nxe_secure_x509_extended_key_usage_extension_parse.o \
./nx_secure/src/nxe_secure_x509_extension_find.o \
./nx_secure/src/nxe_secure_x509_key_usage_extension_parse.o 


# Each subdirectory must supply rules for building sources it contributes
nx_secure/src/%.o: ../nx_secure/src/%.c
	arm-none-eabi-gcc -mcpu=cortex-a9 -march=armv7-a -marm -mlittle-endian -mfloat-abi=hard -mfpu=vfpv3-d16 -O3 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wnull-dereference -g -Wstack-usage=2000 -I../../filex/ports/cortex_a9/gnu/inc -I../../filex/common/inc -I../../threadx/common/inc -I../../rz_bsp/azure/ports/cortex_a9/gnu/inc -I../../netxduo/common/inc -I../../netxduo/crypto_libraries/inc -I../../netxduo/nx_secure/ports -I../../netxduo/nx_secure/inc -I../../netxduo/addons/azure_iot -I../../netxduo/addons/azure_iot/azure-sdk-for-c/sdk/inc -I../../netxduo/addons/azure_iot/azure_iot_security_module/iot-security-module-core/inc -I../../netxduo/addons/azure_iot/azure_iot_security_module/inc -I../../netxduo/addons/azure_iot/azure_iot_security_module -I../../netxduo/addons/azure_iot/azure_iot_security_module/iot-security-module-core/deps/flatcc/src/runtime -I../../netxduo/addons/azure_iot/azure_iot_security_module/iot-security-module-core/deps/flatcc/include -I../../netxduo/addons/cloud -I../../netxduo/addons/mqtt -I../../netxduo/addons/dns -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"

